### ISSUE TITLE
The version of device should not displayed under the name iphone 8 and iphone 8 plus

### ISSUE THREAD

**Issue by dhreben** [zebrunner/stf#139]
Steps:
1.Open http://stf-stage.solvd.com/#!/devices
2.Enter your login and password
3.Tap details
Actual result: The version of device should not displayed under the name iphone 8 and iphone 8 plus
<img width="886" alt="Screen Shot 2020-03-24 at 15 57 43" src="https://user-images.githubusercontent.com/50950954/77428063-8b972480-6de8-11ea-81a6-3ef3e2235b75.png">

**Comment by vdelendik** [comment]
fixed. versions shouldn't be added anymore to device names

**Comment by dhreben** [comment]
**Test scenario:**

1.Open `stage.solvd.com /stf`
2.Enter your login and password

**Actual result**: Versions  are presented on device names

<img width="933" alt="Screenshot 2020-12-22 at 16 55 31" src="https://user-images.githubusercontent.com/50950954/102896236-193a9a00-4477-11eb-8a4f-bcb29fcf9601.png">

**Comment by vdelendik** [comment]
fixed during huge refactoring for new engine based on ios-go: https://github.com/zebrunner/stf/pull/242
device name provided in main.yml will be registered as for Androids

**Comment by dhreben** [comment]
Fixed
<img width="954" alt="Screenshot 2021-12-16 at 13 19 34" src="https://user-images.githubusercontent.com/50950954/146353430-be3b2ca4-53f1-4152-967b-14037ec2ee36.png">
