### ISSUE TITLE
Not able to unlock iOS device

### ISSUE THREAD

**Issue by kolyakrasnik** [zebrunner/stf#145]
We are not able to unlock iOS device. Clicking on power button in STF doesn't change anything (black screen). After unlocking the device STF works without issues.

**Comment by shov** [comment]
@kolyakrasnik which versions of devices / ios it can be reproduced on?

**Comment by kolyakrasnik** [comment]
@shov The issue was reproducible on iOS 13.2. I guess you can also check higher version as they are already available.

**Comment by vdelendik** [comment]
it is repro only on specific devices/setup. moved to 3.3 milestone

**Comment by vdelendik** [comment]
fixed. during the testing make sure you can unlock click home button and entering pin
