### ISSUE TITLE
unable to start ios device sevices

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#166]
Cannot find module 'stf-syrup'.
we have to update all require calls using:
var syrup = require('stf-syrup')
->
var syrup = require('@devicefarmer/stf-syrup')

**Comment by vdelendik** [comment]
fixed: https://github.com/zebrunner/stf/pull/167

as test scenario follow https://github.com/zebrunner/mcloud-ios/blob/develop/README.md steps to connect ios device correctly

**Comment by dhreben** [comment]
Verified.
