### ISSUE TITLE
investigate possibility to register appiumUrl as relative url to stf

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#171]
http(s)://hostname/mcloud/appium/private_host/port
http(s)://hostname/mcloud/appium/udid/private_host/port

--public-node-ip argument should be removed either in stf so in mcloud-ios

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/stf/pull/172

mcloud should provide only appium host as stf public host and dynamic proxy appium port

**Comment by dhreben** [comment]
I can check after fixed https://github.com/zebrunner/mcloud-ios/issues/16

**Comment by dhreben** [comment]
Verified.
