### ISSUE TITLE
Appium displays incorrect URL  http://127.0.0.1:7710/wd/hub

### ISSUE THREAD

**Issue by dhreben** [zebrunner/stf#173]
**Test scenario:**

1. Start STF
2.Occupy device and open "Automation" tab
-> Appium url should be somethig like http://public-ip:7403/wd/hub
Try to do any call to this shared appium url, for example /status
curl http://myhost:7403/wd/hub/status
-> appium should return it's status and version in output
3. Stop usage for device
4. again execute status call curl http://myhost:7403/wd/hub/status
-> this time error message should appear

curl: (7) Failed to connect to myhost port 7403: Connection refused

**Action result**: Appium displays incorrect URL  http://127.0.0.1:7710/wd/hub

Please see screenshot:

<img width="1043" alt="Screenshot 2020-12-16 at 17 08 07" src="https://user-images.githubusercontent.com/50950954/102359022-54ddeb80-3fc1-11eb-8ab5-e7ccb5095b40.png">

**Comment by vdelendik** [comment]
fixed. it should be tested using develop branch of stf and mcloud-ios.
private stf_node_host ip should be disaplyed in the url

**Comment by dhreben** [comment]
Fixed:

<img width="1233" alt="Screenshot 2020-12-21 at 19 33 01" src="https://user-images.githubusercontent.com/50950954/102799287-61988000-43c3-11eb-8c3c-1a399f3e0819.png">
