### ISSUE TITLE
Landscape mode doesn't display properly

### ISSUE THREAD

**Issue by dhreben** [zebrunner/stf#177]
**Test scenario:**

1. Open http://stage.solvd.com/stf
2. Open iPad or iPhone
3. Tap landscape mode

**Actual result:** Landscape mode doesn't display properly
Please see screenshot:

<img width="911" alt="Screenshot 2020-12-30 at 17 21 50" src="https://user-images.githubusercontent.com/50950954/103357151-85467f00-4ac3-11eb-8df5-8f7742da877b.png">

**Comment by Veeru5c4** [comment]
I have also same issue

Landscape mode doesn't display properly and touches also not working properly
touches are mismatch

Please help this issue

**Comment by vdelendik** [comment]
tried to disable rotation for iOS devices using ` --lock-rotation` but still UI allow to make it happen so waiting for the valid fix.

**Comment by vdelendik** [comment]
related ticket with valid info from dev: https://github.com/zebrunner/stf/issues/48

**Comment by ignacionar** [comment]
**Done:** https://github.com/zebrunner/stf/pull/769

Full details in PR

**Comment by vdelendik** [comment]
```
The folllowing changes fix tapping and swiping in Landscape mode for iOS devices.

After trying and failing several times, I found a working configuration for the scaling service in iOS devices:

- The width/height boundaries need to remain as the same as before.

- Both `x` and `y` coordinates work differently in iOS. The `x` coordinate value needs to be set with `relY` value and the `y` coordinate with the `relX` value.

- The `xP` and `yP` need to switch their values for iOS.

- The coords function now receives `device.ios` as an argument, to check the device OS and use the correct configuration (in Android the Landscape mode works fine, so no need to change its logic)

- Finally both Landscape/Portrait mode swiping works the same way.
 
```

**Comment by dhreben** [comment]
Reopened

Steps:

1. Open iphone_12 on STF
2. Click Safari or Photos
3. Click Landscape button - > device has turned to Landscape mode
4. Click Home button

Actual result: The screen of the device has decreased in size, as well as swipes and clicks do not work properly

<img width="385" alt="Screenshot 2023-08-11 at 11 44 09" src="https://github.com/zebrunner/stf/assets/50950954/426c30e6-feb3-4773-ae79-3305903cbbd4">

**Comment by dhreben** [comment]
Closed. Opened separate ticket https://github.com/zebrunner/stf/issues/770
