### ISSUE TITLE
Navigation not working

### ISSUE THREAD

**Issue by Veeru5c4** [zebrunner/stf#179]
I have setup iphone devices up and running working fine but in portal navigation not working getting error logs

 Failed to send request with error { StatusCodeError: 500 - {"value":{"error":"session not created","message":"'capabilities' is mandatory to create a new session","traceback":""},"sessionId":"CB87B970-E07F-4324-B397-5F8996E4A56F"}
    at new StatusCodeError (/Users/veeraswamygajula/Projects/mcloud-ios/stf/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/Users/veeraswamygajula/Projects/mcloud-ios/stf/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/Users/veeraswamygajula/Projects/mcloud-ios/stf/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/Users/veeraswamygajula/Projects/mcloud-ios/stf/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/Users/veeraswamygajula/Projects/mcloud-ios/stf/node_modules/request/request.js:1154:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/Users/veeraswamygajula/Projects/mcloud-ios/stf/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
  name: 'StatusCodeError',
  statusCode: 500,
  message: '500 - {"value":{"error":"session not created","message":"\'capabilities\' is mandatory to create a new session","traceback":""},"sessionId":"CB87B970-E07F-4324-B397-5F8996E4A56F"}',
  error: 
   { value: 
      { error: 'session not created',
        message: '\'capabilities\' is mandatory to create a new session',
        traceback: '' },
     sessionId: 'CB87B970-E07F-4324-B397-5F8996E4A56F' },
  options: 
   { method: 'POST',
     uri: 'http://192.168.0.3:20011/session/',
     body: { desiredCapabilities: [Object] },
     json: true,
     callback: [Function: RP$callback],
     transform: undefined,
     simple: true,
     resolveWithFullResponse: false,
     transform2xxOnly: false },
  response: 
   IncomingMessage {
     _readableState: 
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [Object],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: true,
        endEmitted: true,
        reading: false,
        sync: true,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: false,
     domain: null,
     _events: 
      { end: [Array],
        close: [Array],
        data: [Function],
        error: [Function] },
     _eventsCount: 4,
     _maxListeners: undefined,
     socket: 
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [Object],
        _parent: null,
        _host: null,
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 315,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [Object],
        [Symbol(asyncId)]: 8466,
        [Symbol(bytesRead)]: 0 },
     connection: 
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [Object],
        _parent: null,
        _host: null,
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 315,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [Object],
        [Symbol(asyncId)]: 8466,
        [Symbol(bytesRead)]: 0 },
     httpVersionMajor: 1,
     httpVersionMinor: 1,
     httpVersion: '1.1',
     complete: true,
     headers: 
      { server: 'WebDriverAgent/1.0',
        'content-type': 'application/json;charset=UTF-8',
        'access-control-allow-origin': '*',
        date: 'Tue, 19 Jan 2021 08:39:01 GMT',
        'access-control-allow-headers': 'Content-Type, X-Requested-With',
        'accept-ranges': 'bytes',
        'content-length': '206',
        connection: 'close' },
     rawHeaders: 
      [ 'Server',
        'WebDriverAgent/1.0',
        'Content-Type',
        'application/json;charset=UTF-8',
        'Access-Control-Allow-Origin',
        '*',
        'Date',
        'Tue, 19 Jan 2021 08:39:01 GMT',
        'Access-Control-Allow-Headers',
        'Content-Type, X-Requested-With',
        'Accept-Ranges',
        'bytes',
        'Content-Length',
        '206',
        'Connection',
        'close' ],
     trailers: {},
     rawTrailers: [],
     aborted: false,
     upgrade: false,
     url: '',
     method: null,
     statusCode: 500,
     statusMessage: 'Internal Server Error',
     client: 
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [Object],
        _parent: null,
        _host: null,
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 315,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [Object],
        [Symbol(asyncId)]: 8466,
        [Symbol(bytesRead)]: 0 },
     _consuming: true,
     _dumped: false,
     req: 
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: null,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'POST /session/ HTTP/1.1\r\nhost: 192.168.0.3:20011\r\naccept: application/json\r\ncontent-type: application/json\r\ncontent-length: 165\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'POST',
        path: '/session/',
        _ended: true,
        res: [Circular],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        [Symbol(outHeadersKey)]: [Object] },
     request: 
      Request {
        domain: null,
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        method: 'POST',
        uri: [Object],
        body: '{"desiredCapabilities":{"bundleId":"com.apple.mobilesafari","arguments":["-u","https://www.google.co.in/imghp?hl=en-GB&tab=ri&ogbl"],"shouldWaitForQuiescence":true}}',
        readable: true,
        writable: true,
        explicitMethod: true,
        _qs: [Object],
        _auth: [Object],
        _oauth: [Object],
        _multipart: [Object],
        _redirect: [Object],
        _tunnel: [Object],
        _rp_resolve: [Function],
        _rp_reject: [Function],
        _rp_promise: [Object],
        _rp_callbackOrig: undefined,
        callback: [Function],
        _rp_options: [Object],
        headers: [Object],
        setHeader: [Function],
        hasHeader: [Function],
        getHeader: [Function],
        removeHeader: [Function],
        localAddress: undefined,
        pool: {},
        dests: [],
        __isRequestRequest: true,
        _callback: [Function: RP$callback],
        proxy: null,
        tunnel: false,
        setHost: true,
        originalCookieHeader: undefined,
        _disableCookies: true,
        _jar: undefined,
        port: '20011',
        host: '192.168.0.3',
        path: '/session/',
        _json: true,
        httpModule: [Object],
        agentClass: [Object],
        agent: [Object],
        _started: true,
        href: 'http://192.168.0.3:20011/session/',
        req: [Object],

**Comment by vdelendik** [comment]
fixed providing valid capabilities. also submitted enhancement: https://github.com/zebrunner/stf/issues/248

**Comment by vdelendik** [comment]
marked as verified. also submitted doc enhancement to configure siri and WDA openURL has a problem on Apple side
