### ISSUE TITLE
appium url is not generated correctly for secured (ssl) config

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#181]
using appium-host and appium-port url is generated using hardcoded http protocol.
we have to detect if https is used and adjust property

related tickets:
https://github.com/zebrunner/mcloud/issues/74
https://github.com/zebrunner/android-device/issues/41

**Comment by vdelendik** [comment]
appium url is http only as we decided to share actual provider host port.
fixed: https://github.com/zebrunner/stf/pull/195

**Comment by dhreben** [comment]
Checked by customer env.
