### ISSUE TITLE
sync with device farmer 3.6.1 release

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#186]
https://github.com/DeviceFarmer/stf/releases/tag/v3.6.1

**Comment by vdelendik** [comment]
https://github.com/zebrunner/stf/pull/188
changes should be tested using zebrunner/stf:1.1-beta1 docker image, i.e. in scope of zebrunner mcloud/,end should be updated in advance

**Comment by dhreben** [comment]
Verified.

<img width="689" alt="Screenshot 2021-04-14 at 19 08 19" src="https://user-images.githubusercontent.com/50950954/114742829-c9008400-9d54-11eb-82aa-f2ce1aac0797.png">

Test scenario to update STF:

1.Git clone zebrunner from develop branch
2../setup zebrunner with all components
3.git clone mcloud-ios
4../setup mcloud-ios
5.git clone Mcloud-android 
6../setup ansible script
7.Open jenkins
8.Management_Jobs
9.Run RegisterHubCredentials with Mcloud provider
10.Open reporting
11.Tap integrations 
12.Check that Mcloud URL have http://demo.zebrunner.farm:80/mcloud/wd/hub
