### ISSUE TITLE
Unable to interact with devices owing to slow performance

### ISSUE THREAD

**Issue by rkatuzhanets** [zebrunner/stf#187]
This issue is actual mostly for iOS platform, when user matches one of the following conditions:

- Current user is working under project's VPN
- Current user is located in different from STF location region

General speed of STF commands' execution is decreased dramatically or, quite often, even simple actions (click on screen, type in input field) couldn't be established. Moreover, there's a slight chance that selected device won't be working at all (just grey screen instead of actual screen state)

**Comment by vdelendik** [comment]
@rkatuzhanets, in upcoming 1.1 release minimized STF_PROVIDER_SCREEN_JPEG_QUALITY from 40 to 30.
Moreover, it will be possible to override this value using device2docker script now sharing any custom values based on actual networking setup.

**Comment by vdelendik** [comment]
it might sense to test a little bit improved for manual usage WDA from
https://github.com/nanoscopic/ControlFloorAgent
https://github.com/nanoscopic/ControlFloorAgent/commit/4aa3818956c5229883f9e77b65eaaebcb0789295

**Comment by vdelendik** [comment]
during 2.0 developing we reproduced several cases when devices sage via STF UI might generate recursive call which break WDA and for users looks like huge slowness.
So in 2.0 completely refactored communication approach between human and device: https://github.com/zebrunner/stf/pull/263
Hopefully it should significantly improve user experience working with iOS devices in MCloud

**Comment by dhreben** [comment]
Verified.
iOS devices are much more stable on Mcloud 2.0
