### ISSUE TITLE
Decommision appium proxies

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#193]
To avoid all kind of network latencies and performance issues we could remove all proxying services for appium and proxy.
In upcoming releases we have to share slave and their ports to the users so there is no need to generate proxy anymore

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/stf/pull/195

we don't start any proxy for appium and just register provider hot and direct appium url for Automation tab

**Comment by dhreben** [comment]
Verified.
