### ISSUE TITLE
share static appium url inside automation tab

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#194]
in automation tab we show appium url which require public address of the slave. we have to review mcloud-ios and mcloud-android and register appium url using stf public host/port with notation like:
http(s)://PUBLIC_IP/appium/NODE_PRIVATE_IP/APPIUM_PORT

also mcloud nginx should redirect all appium/* requests into the appropriate private ip/port

**Comment by vdelendik** [comment]
fixed: https://github.com/zebrunner/stf/pull/195
static provider host and appium url was reused to make it happen

**Comment by dhreben** [comment]
Verified.
