### ISSUE TITLE
"cli device" for android sometimes can't be started from 1st attempt

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#198]
we have to detect root cause of the non started `cli device` node service from first attempts
stf\lib\units\provider\index.js
```
      else if (lists.ready.length < lists.all.length) {
        log.info(
          'Providing all %d of %d device(s); ignoring "%s"'
        , lists.ready.length
        , lists.all.length
        , _.difference(lists.all, lists.ready).join('", "')
        )
      }
```

**Comment by vdelendik** [comment]
it is fixed indirectly after redesigning android-device container. as only we migrate to 2.0 stf should be started in 5-10 sec which is super fast in comparison with current 20-30s

**Comment by dhreben** [comment]
Fixed
