### ISSUE TITLE
Change stf logo to zebrunner logo

### ISSUE THREAD

**Issue by dhreben** [zebrunner/stf#202]
Let's upgrade logo and change stf to zebrunner logo

![Screen Shot 2021-04-30 at 3 47 15 PM](https://user-images.githubusercontent.com/50950954/116697103-73221200-a9cb-11eb-9ab6-4a9af083f60a.png)

**Comment by vdelendik** [comment]
done. changes might be tested on demo env
![image](https://user-images.githubusercontent.com/4551455/182146654-060fbaed-6f98-4019-85e0-2fa1811681ef.png)
