### ISSUE TITLE
I am not able install iPa file via UI

### ISSUE THREAD

**Issue by Veeru5c4** [zebrunner/stf#210]
Hi,

I tried to install ipa file in iOS device via UI getting error ''opps no input files''
please help this issue

**Comment by vdelendik** [comment]
Hey @Veeru5c4.
So far it is impossible to do via UI. We recommend to open ssh access and use cli tools as of now. Installing ipa especially in develoment mode requires too mauchextra efforts to do so feature is not support as of now.

**Comment by vdelendik** [comment]
feature is here: https://github.com/zebrunner/stf/issues/245
