### ISSUE TITLE
investigate if we need STF_PROVIDER_APPIUM_PORT and all kind of forwarding logic

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#234]
STF_PROVIDER_APPIUM_PORT was used as a port forwarding proxy service to share temporary direct access to appium using STF.
in upcoming 2.x generation appium services moved into the independent container and this port is more or less static and shared to the mcloud grid server. it seems like inside stf we can only register this value and show (still needed and why?)

in scope of the ticket obligatory review stf code and remove all kind of port forwarding if any.
if we decide to remove it completely we should adjust mcloud-android repo as well

**Comment by vdelendik** [comment]
inspect existing stf sources and removed all references to:
```
appium-port
--appium-port
--host
Provider hostname
remoteAppiumUrl
UpdateRemoteConnectUrl
appium-remote-debug
```

we have to review mcloud-device startup scrips and remove such cli args:
```
--appium-port
--host
```


changes are available in `zebrunner/stf:2.4-beta6`.
to test we have to setup CE using develop branch, make sure `stf:2.4-beta6` inside your mcloud/.env file. And setup mcloud-agent from develop (make sure mcloud-device:2.4-beta6 inside defauls/main.yml).

1. stf should be started succesfully, devices registered and available
2. there is no information about Appium Url inside Automation tab (force reload or browser cache cleanup might be required)
3. reuse devices manually and via automation running ios and android jobs

**Comment by dhreben** [comment]
Will be verified after fixed https://github.com/zebrunner/community-edition/issues/532

**Comment by dhreben** [comment]
Verified with CE+ec2.
Tested manually and automated behaviour.
