### ISSUE TITLE
ios-device: make it ios-deploy independent

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#236]
let's try to reorganize code and make stf ios-device service as much independent from ios-deploy as possible.
stf ios-device should just receive info from external service and register as is (potentially we could implement provider for ios as well)

**Comment by vdelendik** [comment]
the most important part is done: https://github.com/zebrunner/stf/pull/242
for the rest problematic places separated tickets submitted: #243, #244, #245

during the testing setup MCloud 2.0 on stage connecting iOS devices to Linux, do basic manual and automated testing

**Comment by dhreben** [comment]
iOS devices work great , except automation. This issue will be solved in 2.1 version
Separated tickets submitted: #243, #244, #245
