### ISSUE TITLE
ios: reuse wda for clipboard operation

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#243]
https://github.com/zebrunner/stf/pull/242/files#diff-ec5f3c1653511152ed6c850d13b41b69261abb99042ea292e70b8017276d1e97R58

wda actions: https://documenter.getpostman.com/view/1837823/TVmMhJNB#88858d05-9d64-4d3c-8808-6c0909caae07
Apple complains: https://developer.apple.com/forums/thread/684548

**Comment by vdelendik** [comment]
move to 2.1 as too many complains exists on XCUITest itself

**Comment by EzequielOmar** [comment]
Done: #700 

Enabled a Post request to WDA server, that gets the host machine clipboard content, and display it in text input clipboard field on STF dashboard.

You have first to manually copy from simulator device, the copied content get stored on host machine clipboard.

Tested on iPhone8 & iPhone14 - OS 16.0 (simulators)
Pending: Test on physical Ios devices.

Same functionality achieved in both Android and Ios, with exceptions:
- On manual copy on Ios simulator device, text get stored in host machine clipboard, so it will be overwritten with posterior copied text on host machine.
- Wda request takes a little bit longer than Android apk request.

**Comment by vdelendik** [comment]
@EzequielOmar - merged.
@dhreben - building new stf, mcloud-device and updating mcloud-agent defaults/main.yml configuration file

**Comment by dhreben** [comment]
Verified.
