### ISSUE TITLE
ios: reuse wda for upload/install app

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#244]
https://github.com/zebrunner/stf/pull/242/files#diff-2b70ce78533f6e5f50e1b19f191d092a7e006140304c0e54e66080df419ced99R264

**Comment by vdelendik** [comment]
blocked until we finish testing of the gray screen on distributed env. so we can proceed with implementation only on Dec, 18

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/stf/pull/388

fully reorganized iOS part supporting as simulators so real devices..
testing should:
1. include http and https setup
2. include testing of read iOS devices and simulators
3. iOS devices connected via Linux mcloud-agent and MacOS mcloud-ios
4. using apk/ipa/zip for iOS and Android devices
-> only supported build artifacts should be installed. For unsupported error message displayed
5. invalid apk/ipa/zip files to demonstrate that installation not even started if no android manifest or info.plist detected
6. recently installed application should be launched automatically

changes should be available in mcloud, mcloud-agent and mcloud-ios repositories, branch: develop.

**Comment by dhreben** [comment]
Verified.
