### ISSUE TITLE
ios: think what to do with existing WDA session on `stop using`

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#246]
As minimal we have to reset existing WdaClient.sessionШd to null obligatory so next attempt will read again actual value from wda/status call.
also let's think if we should completely destroy existing session. Maybe it has sense to keep in the local var how initialize was done, i.e. if we started new wda session at opening then kill this session on `stop using`. If any existing session was discovered then keep as is to nor affected automation runs if any

**Comment by vdelendik** [comment]
https://github.com/zebrunner/stf/pull/263

wda session is started automatically on start using and stopped on stop.

**Comment by dhreben** [comment]
Verified.
