### ISSUE TITLE
ios: improve openURL to reuse already activated safari if any

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#248]
we do everytime new wda session for safari but it would be great to detect existing and open inside current session.
for example such command
`curl --location -g --request GET '{{baseURL}}/wda/activeAppInfo'`
returns 
```
{
  "value" : {
    "processArguments" : {
      "env" : {

      },
      "args" : [

      ]
    },
    "name" : "",
    "pid" : 60,
    "bundleId" : "com.apple.springboard"
  },
  "sessionId" : "C0D1CBB9-E5EE-4FD3-AA44-A6073862DAF7"
}
```

**Comment by vdelendik** [comment]
1. there is no way to open url via WebDriverAgent due to the bug in Apple:
https://developer.apple.com/forums/thread/25355
2. Appium suggested to use Siri functionality for that, i.e. to be able to open via STF UI we have to enable Siri obligatory
https://github.com/appium/WebDriverAgent/pull/49
3. removed all session stop/star toperation as it is enough to call only `/url`

**Comment by dhreben** [comment]
Verified.
Open separate ticket https://github.com/zebrunner/stf/issues/295
