### ISSUE TITLE
move go-ios utility from appium into the stf

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#254]
In comparison with android where we can forward commands via adb for iOS it is impossible.
Moreover, there are set of requests which require access to iOS devices on low level:
https://github.com/zebrunner/stf/issues/249
https://github.com/zebrunner/stf/issues/246
https://github.com/zebrunner/stf/issues/245

seems like we have to move go-ios into the stf instead of Appium and provide to appium only links to WDA.

**Comment by vdelendik** [comment]
done, go-ios moved onto the stf -> android-device images to be able to reuse direct WDA connection for all kind of communications between stf ios-device service and device

**Comment by dhreben** [comment]
Verified
