### ISSUE TITLE
2.0: pair ios device 

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#256]
paring seems needed to be able to activate connection between Linux server and iOS device after reboot or recovery.
1. establish pairing
2. collect required steps for docs
3. reboot iOS device
-> after restarting it should be connected automatically
4. reboot Linux
-> after server restart iOS device is available and already trusted

**Comment by vdelendik** [comment]
fixed in a little bit limited format. Also submitted new enhancement for much more stable solution: https://github.com/zebrunner/stf/issues/280

so during the testing we have to verify modified steps in comparison with ticket description:
1. connect iOS device, click Trust
2. start ios-device service using `zebrunner-farm start <udid>`
-> device is accessible via STF
3. restart service using `zebrunner-farm restart <udid>`
-> service restart, device reconnected automatically
4. reboot iOS device
5. right after reboot question about `Trust` should appear and we have to test both scenarios with not trust and trust
-> when no trust selected ios device container will be restarted forcibly
-> when trusted is selected ios device should be started this or next time
6. reboot Linux server itself
-> ideally all iOS devices reconnected automatically (if not - just submit a new ticket and close this one)

collect required steps for docs
reboot iOS device
-> after restarting it should be connected automatically
reboot Linux
-> after server restart iOS device is available and already trusted

**Comment by dhreben** [comment]
Verified.
After checked 6 steps opened separate ticket https://github.com/zebrunner/mcloud-android/issues/60
