### ISSUE TITLE
ios: find a way to init device data without recursive http calls

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#258]
to init device data we need size, maybe orientation etc.
all this information might be accessible via go-ios utility which could be ideal because size is permanent and depends on version etc.
as about runtime data about battery, sdk etc - as of now we can remove it at all...

Goal: exclude recursive http calls to mitigate wda crash risks

**Comment by vdelendik** [comment]
completely removed proxying and potential recursive failures by size init right after wda session start:
https://github.com/zebrunner/stf/pull/263

**Comment by okamara** [comment]
Verified, fixed.
