### ISSUE TITLE
ios: During typing text Disconnect pop-up apperas

### ISSUE THREAD

**Issue by okamara** [zebrunner/stf#268]
Steps:
1. Open stf by url
2. Open ios device
3. Open application or browser 
4. Start typing
Actual result: During typing text Disconnect pop-up appeared
Expected: During typing text no any Disconnect pop-ups
<img width="1260" alt="Снимок экрана 2021-12-16 в 11 00 11" src="https://user-images.githubusercontent.com/32964663/146341589-267e2cc8-24fc-4043-a319-d98b588e9a0b.png">

**Comment by vdelendik** [comment]
we should ignore invalid typing and don't reject promise...

**Comment by vdelendik** [comment]
fixed: https://github.com/zebrunner/stf/pull/279
device will ignore types in invalid places and will operate to slow but without crashes

**Comment by okamara** [comment]
Verified on iphone 8 plus
