### ISSUE TITLE
The screen does not hide after pressing a  'Hide screen' button

### ISSUE THREAD

**Issue by dhreben** [zebrunner/stf#270]
**Steps:**

1. Open STF
2. Enter your login and password
3. Open any iOS or Android devices
4. Click 'Hide screen' button

**Actual result**:  The screen does not hide after pressing a  'Hide screen' button

**Expected result:**  The screen  hides after pressing a 'Hide screen' button

![Screenshot 2021-12-17 at 12 15 05](https://user-images.githubusercontent.com/50950954/146519908-e2bab538-ac7d-490f-9324-d7ccec7dae61.png)

**Comment by vdelendik** [comment]
closing as can't reproduce. @dhreben, need more details about use-case, maybe specific browser etc

**Comment by dhreben** [comment]
The issue is reproduced on MacOS Big Sur Version 11.6.1 
Only on connected 2560×1440 pixels monitor with Split mode
Chrome browser Version 96.0.4

![Screenshot 2021-12-21 at 13 24 53](https://user-images.githubusercontent.com/50950954/146914381-f65932f1-0cc0-4310-a27b-16c0bbcc4914.png)

**Comment by dhreben** [comment]
Not supported MacOS with Split mode
Closed.
