### ISSUE TITLE
There are Face Time, Camera, Mail, Clock,Weather, Reminders and Notes buttons don't clickable in special area of the screen on the main menu

### ISSUE THREAD

**Issue by dhreben** [zebrunner/stf#271]
**Steps:**

1. Open STF
2. Enter your login and password
3. Open any iOS devices

**Actual result:**   There are Face Time, Camera, Mail, Clock, Weather, Reminders, and Notes buttons are not clickable in a special area of the screen on the main menu.

**Expected result:**  All the buttons in this area are clickable and work.

However, if I move any of the buttons outside of that area of the screen, they become active

**Please see screenshot:**

![Screenshot 2021-12-17 at 12 54 41](https://user-images.githubusercontent.com/50950954/146525933-0584ede8-b484-4b24-ac36-3e3fac16afcb.png)

**Comment by vdelendik** [comment]
closing as can't reproduce. @dhreben, provide more details about your browser, resolution etc if you still see the problem

**Comment by dhreben** [comment]
The issue is reproduced on MacOS Big Sur Version 11.6.1
Only on connected 2560×1440 pixels monitor with Split mode
Chrome browser Version 96.0.4

![Screenshot 2021-12-21 at 13 50 01](https://user-images.githubusercontent.com/50950954/146918050-d4df732f-1fc6-4665-8850-2f14c177fcaa.png)

**Comment by dhreben** [comment]
Not supported MacOS with Split mode
Closed.
