### ISSUE TITLE
populating ios device info was broken (platform, version, size, battery info etc)

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#284]
Let return back general info population and sending it into the STF db to be able to handle OS upgrade etc.
It would be great to init and send this data at once only right after start and don't request again and again for every session but do smart analysis because battery state maybe better to sync on every connect.

original cleanup to simplify as much as possible for 2.0 upgrade can be found here: https://github.com/zebrunner/stf/commit/3b197b83e71aca824c92cdd3eb278700edba6498#diff-c0e662c394d4f7f25b37555bc7982efa0f05f9595025a9cb82e9c4fec91884c4

**Comment by vdelendik** [comment]
fixed. height/width, os version and battery level should be updated after each device occupy operation.
Note: it is ok that data is updated only for the next session

**Comment by dhreben** [comment]
Fixed.
The incorrect screen resolution (height/width ) displays on the info state
A relevant ticket has been opened : https://github.com/zebrunner/stf/issues/292
