### ISSUE TITLE
ios battery level and state not displayed on details devices view

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#289]
After fixing #284 we are able to send battery level (0..1*100 as percent) and state which is a number (2 seems Fully Charged).
But battery level is displayed only on Info page:
![image](https://user-images.githubusercontent.com/4551455/147411410-0a7db8ed-e982-444c-af3e-e6bc35455951.png)

but on devices details view:
![image](https://user-images.githubusercontent.com/4551455/147411438-23bf56b1-5ab6-488b-8dda-5b110e3aa635.png)

let's investigate what else might be discovered, maybe on startup using go-ios like power source and at run time

**Comment by vdelendik** [comment]
fixed:
![image](https://user-images.githubusercontent.com/4551455/182185535-a30e3fc3-8d43-4d70-9f26-64ec33516c2c.png)

stf:2.3-beta10+

**Comment by dhreben** [comment]
Verified.
