### ISSUE TITLE
combine manual and automated wda session usage for iOS devices

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#290]
WdaClient,js starts new WDA session everytime we occupy device.
Let's investigate use-case when device is occupied by automation and user just open already existing session.

Hopefully, when we open already activated device we don't start new wda and don't corrupt automation. but at the same time we have to double check that sessionId can be detected so user can help to automation scenarios correctly making any action vs existing WDA session

**Comment by vdelendik** [comment]
in #285 (PR: https://github.com/zebrunner/stf/pull/291) we already improved WDA session tracking.
in scope of this ticket verify what's going on if we open already activated device by API and what to do when we call stop using.

as of now logic might be:
1. currently activated app us shown
2. current WDA session id is populated and used by STF (means user can help to click/swipe etc for existing appium session)
3. on manual `stop usage` forcibly kill wda session even in spite of the fact that automation might be broken. If you wanna to wait till finish you shouldn't do `stop using` via UI

**Comment by dhreben** [comment]
Verified.
