### ISSUE TITLE
iOS: The incorrect screen resolution displays on the info state

### ISSUE THREAD

**Issue by dhreben** [zebrunner/stf#292]
**Steps:**

1.Open STF
2.Open any iOS device
3 Click info button

**Actual result:**  The incorrect screen resolution (height/width ) displays on the info state

![Screenshot 2021-12-27 at 14 08 17](https://user-images.githubusercontent.com/50950954/147466156-1b28ac34-e205-4850-9776-07b048558d2a.png)

**Comment by vdelendik** [comment]
We have to adjust resolution using scaling factor doing 2 calls:
 curl http://192.168.88.29:20001/session/7D603C61-996B-40F9-923D-C27E9F9B5C13/window/size
{
  "value" : {
    "width" : 375,
    "height" : 667
  },
  "sessionId" : "7D603C61-996B-40F9-923D-C27E9F9B5C13"
}

and 
curl http://192.168.88.29:20001/session/7D603C61-996B-40F9-923D-C27E9F9B5C13/wda/screen
{
  "value" : {
    "statusBarSize" : {
      "width" : 375,
      "height" : 20
    },
    "scale" : 2
  },
  "sessionId" : "7D603C61-996B-40F9-923D-C27E9F9B5C13"
}

actual size should be width*scale. For detals take a look to the table of sizes and dimensions:
![image](https://user-images.githubusercontent.com/4551455/150423033-276bca43-0749-4fb6-89d4-142efc569410.png)

**Comment by vdelendik** [comment]
done calculation height/width using scale factor:
![image](https://user-images.githubusercontent.com/4551455/182205711-3e83e199-62ed-483c-ae1a-4e58cd816816.png)

**Comment by dhreben** [comment]
Verified.
