### ISSUE TITLE
ios: Verify that it is possible upload app via app loader

### ISSUE THREAD

**Issue by okamara** [zebrunner/stf#294]
Steps:
1. Sign in to stf
2. Open ios device
3. Drag and drop file for Upload "test.ipa"
Actual result: "No input files error appears" and file not loaded
Expected: File is uploaded

<img width="906" alt="Снимок экрана 2021-12-29 в 16 20 45" src="https://user-images.githubusercontent.com/32964663/147674145-0aa6d95b-083b-4b0a-bde0-644798b85464.png">

**Comment by okamara** [comment]
[MegaWeather 3.2.6.ipa.zip](https://github.com/zebrunner/stf/files/7789443/MegaWeather.3.2.6.ipa.zip)

**Comment by vdelendik** [comment]
fixed in scope of #244 feature. testing scenarios also described in that ticket...

**Comment by dhreben** [comment]
Verified upload ipa and zip formats
