### ISSUE TITLE
Shell is visible for ios but not working (need hide)

### ISSUE THREAD

**Issue by okamara** [zebrunner/stf#296]
Steps:

1. Sign in to stf
2. Open ios device
3. Verify that Shell is not visible for ios(not working this option)
Actual result: Shell is visible for ios but not working
Expected: Shell is not visible for ios
<img width="484" alt="Снимок экрана 2021-12-30 в 14 20 22" src="https://user-images.githubusercontent.com/32964663/147747709-e05aabc9-35b0-4879-bea3-965e50bf6a08.png">

**Comment by vdelendik** [comment]
removed shell controls completely for iOS devices
![image](https://user-images.githubusercontent.com/4551455/182166625-e408285a-fb72-4e88-abce-e65e75299149.png)

stf:2.3-beta8+ has a fix
