### ISSUE TITLE
iOS:Developer and Manage apps options not working (need hide or fix)

### ISSUE THREAD

**Issue by okamara** [zebrunner/stf#297]
Steps:
1. Open and sign in to stf
2. Open ios device
3. In Apps click Developer and verify that this option is working
4. In Apps click Manage apps and verify that this option is working
Actual result: after clicking on Developer and Manage apps nothing happens
Expected: need hide or fix Developer and Manage apps options
<img width="892" alt="Снимок экрана 2021-12-30 в 14 31 36" src="https://user-images.githubusercontent.com/32964663/147748846-672e70e1-8307-4e89-bd27-d81677b2be4a.png">

**Comment by vdelendik** [comment]
let's investigate possibility to open setting and activate Developer option

**Comment by vdelendik** [comment]
disabled these buttons for iOS
![image](https://user-images.githubusercontent.com/4551455/182172931-fe4c3f4b-c759-4e07-8ce1-fd9ebf951754.png)

2.3-beta9+

**Comment by dhreben** [comment]
Verified.
