### ISSUE TITLE
android: Develop option is not working in Apps

### ISSUE THREAD

**Issue by okamara** [zebrunner/stf#299]
Steps:
1. Open and sign in to stf
2. Open android device
3. In Apps click Develop and verify that Develop is opened on device
Actual result: nothing happens 
Expected: Develop is opened on device

<img width="933" alt="Снимок экрана 2021-12-30 в 15 25 05" src="https://user-images.githubusercontent.com/32964663/147752159-db0e7e05-e569-4f71-9f87-93354a1bb0c9.png">

**Comment by vdelendik** [comment]
closing as can't reproduce. before click on `Develover` make sure to activate and unlock device!

**Comment by dhreben** [comment]
Closing as can't reproduce.
