### ISSUE TITLE
deliver enhanced api to manipulate devices

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#300]
1. it would be great to have api to change device status, i.e. forcibly send to Disconnected when we stop something
2. be able to remove device from DB at all (similar ticket already exists in upstream stf)

**Comment by VbKoshak** [comment]
1. in progress
2. Already implemented under `/api/v1/devices/{serial}`
3. in progress

**Comment by vdelendik** [comment]
closing having 1st request implemented only.

**Comment by dhreben** [comment]
Closed
