### ISSUE TITLE
Android: The device can be disconnected after disable developer options

### ISSUE THREAD

**Issue by dhreben** [zebrunner/stf#302]
**Steps:**

1. Open STF
2. Enter your login and password
3. Open any iOS or Android devices
4. Open developer options
5. Switch off developer options

**Actual result:** The device can be  disconnected after disable developer options

**Comment by vdelendik** [comment]
added won't fix label so far. that's your private cloud and if you want you can remove device from the pool by above steps:)
not sure we can identify this particular click/tap and disable action...
