### ISSUE TITLE
Hide "Automation" tab with fields

### ISSUE THREAD

**Issue by okamara** [zebrunner/stf#304]
Steps:
1. Open STF
2.  Sign in to stf
3.  Select device ios or android
Actual result:"Automation" tab with fields that not used is present
Expected: Hide "Automation" tab with fields
<img width="876" alt="Снимок экрана 2022-01-03 в 15 28 59" src="https://user-images.githubusercontent.com/32964663/147936484-ad569c1c-1172-431c-9837-f000d6e57029.png">

**Comment by vdelendik** [comment]
done. Automation tab is removed in `zebrunner/stf:2.4-beta7`+ version. make sure to clear cache in advance for your browser to test

**Comment by dhreben** [comment]
Fixed
