### ISSUE TITLE
Add an ability to install builds directly from S3 using STF UI

### ISSUE THREAD

**Issue by ivsereda** [zebrunner/stf#305]
**Is your feature request related to a problem? Please describe.**
Sometimes we need to test/check particular build on particular phone, and getting it installed is not easy without access to CI on project

**Describe the solution you'd like**
Add a tab or window in UI with access to S3 bucket with builds uploaded by CI.
Add an ability to pick a build and get it installed onto desired device 
Add and ability to delete the build from device after testing

**Comment by okamara** [comment]
verified via mac, possible upload apk, install, uninstall. 
Impossible install application via url

**Comment by vdelendik** [comment]
@okamara, Android works well using url for apk file in URL navigation on Mac. On Windows I can easily resuse web protocol for browse files dialog as well.
As about iOS it is blocked by https://github.com/zebrunner/stf/issues/244.
Resolving this request to test on Android updating subject accordingly...

**Comment by vdelendik** [comment]
@okamara, @ivsereda: for android it is possible to insert link to the build on storage into the navigation url for browser. As result STF correctly inspect it and if access to apk exists - automatically install on device. For iOS it should be available after fixing #244 (assigned to upcoming 2.1)
