### ISSUE TITLE
Replace device icons in STF

### ISSUE THREAD

**Issue by ivsereda** [zebrunner/stf#341]
**What is the issue or idea you have?**

Device icons are out of date and are the same for all of the device types

**Please provide the steps to reproduce the issue.**

go to STF and see

If we can get different icons for android and iOS at least (and for iPads - nice to have) it would improve UX a little bit

**Comment by vdelendik** [comment]
done. changes are available in `stf:2.4-beta9`. going to incorporate soon into the Mcloud develop and CE develop branches.
make sure to clear cache as icons might be old black one

**Comment by dhreben** [comment]
Verified.
