### ISSUE TITLE
Screenshot's not working on iOS devices

### ISSUE THREAD

**Issue by dhreben** [zebrunner/stf#361]
**Steps:**

1. Open STF
2. Enter your login and password
3. Open iOS device e.g Iphone 8
4. Tap screenshot

**Actual result:** Screenshot's not working on iOS devices

Repro on stage (mcloud-ios + iphone 8) and MFP  (mcloud-agent+ ipad mini )

Nothing happens in the logs after  click the screenshot button

<img width="549" alt="Screenshot 2022-03-10 at 18 51 33" src="https://user-images.githubusercontent.com/50950954/157699897-7923c829-de41-4b63-b3ea-1dc4f3b66edf.png">
<img width="635" alt="Screenshot 2022-03-10 at 18 51 10" src="https://user-images.githubusercontent.com/50950954/157699833-52f9dc9c-3f76-4f4f-8658-634dbb1ae3fd.png">

**Comment by vdelendik** [comment]
closing as fixed indirectly... potentially it was fixed as part of ipa/app install where I adjusted temp storage path for iOS.

**Comment by dhreben** [comment]
Verified.
