### ISSUE TITLE
Find Bundle id used plist util

### ISSUE THREAD

**Issue by dhreben** [zebrunner/stf#384]
We need to find bundle Id .It is a unique identifier for the application, which can be registered, changed and deleted.
Plist util will be used for this.
https://github.com/zebrunner/stf/issues/294

**Comment by vdelendik** [comment]
listplist-utils identified for stf-storage-plugin-apk (ubuntu docker image) to be able to convert Info.plist to xml:
https://github.com/zebrunner/stf/pull/388/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R22

no need to verify the ticket as work still in progress
