### ISSUE TITLE
adjust ipa/app installing progress bar using iOS details

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#395]
average stat for iOS is a little bit different so we have to adjust progress bar ranges based on such data:
real device (220Mb ipa):
uploading - 21s
processing - 1s
pushing - 4s
installing - 17s
launching - 1s

simulator (15Mb app):
uploading - 2s
processing - 0.5s
pushing - 0.5s
installing - 1.5s
launching - 1s

so installing range should be increased

**Comment by vdelendik** [comment]
so as uploading and installing are the slowest new ranges applied:
uploading: 0..50%
processing: no changes (0?)
pushing: 50-60%
installing: 60-95%
launching: 95-100%

changes are deployed on demo using develop branch

**Comment by dhreben** [comment]
Verified.
uploading: 0..50%
processing: without percent
pushing: 50-60%
installing: 60-96%
launching: 97-100%
