### ISSUE TITLE
handle the most popular ipa/app install failure

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#403]
let's analyze failure and return better error message for this particular case instead of INSTALL_ERROR_UNKNOWN
```
{"err":"your app is not properly signed for this device, check your codesigning and provisioningprofile. original error: 'ApplicationVerificationFailed' errorDescription:'Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.ErnMbe/extracted/Payload/MyFitnessPal.app : 0xe8008015 (A valid provisioning profile for this executable was not found.)'","level":"fatal","msg":"failed writing","time":"2022-04-20T12:15:04Z"}
```

**Comment by vdelendik** [comment]
done, for incorrectly signed ipa such message should be displayed
![image](https://user-images.githubusercontent.com/4551455/164235682-9001eda8-a0ca-434b-bd9f-503bd95cb600.png)

**Comment by dhreben** [comment]
Verified

<img width="524" alt="Screenshot 2022-04-20 at 16 37 11" src="https://user-images.githubusercontent.com/50950954/164242936-038cb14d-38ba-47f9-811b-1a55ce819ac3.png">
