### ISSUE TITLE
There is invalid error message after upload zip files on STF via iOS device

### ISSUE THREAD

**Issue by dhreben** [zebrunner/stf#404]
**Steps:**

1.Open STF
2.Open iOS device
3.Upload zip file

**Actual result:** There is invalid error message after upload zip files on STF via iOS device

<img width="597" alt="Screenshot 2022-04-20 at 16 29 42" src="https://user-images.githubusercontent.com/50950954/164241421-9cdb43a4-44fa-4374-ad75-a479a4de5d22.png">

**Comment by vdelendik** [comment]
it should be fixed. stf:2.4.5 published.

**Comment by ignacionar** [comment]
Check this PR: https://github.com/zebrunner/stf/pull/732

It's also necessary to make cache cleanup before the testing

**Comment by dhreben** [comment]
Fixed
