### ISSUE TITLE
iOS: try to change device state to Preparing while wda is starting

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#410]
let's try to implement similar approach as for android when we show preparing state.
for now we do nothing and only when wda is up&running including 1st session we move device state to available

**Comment by ignacionar** [comment]
**Done:** https://github.com/zebrunner/stf/pull/780

**Comment by vdelendik** [comment]
reopening as device is in available state but we can't click use!
https://github.com/zebrunner/stf/pull/783

![image](https://github.com/zebrunner/stf/assets/4551455/a5188ee1-9a34-45bb-a9d6-630bd6778988)

**Comment by vdelendik** [comment]
let's make an attempt to test in 2.5.3:
```
public.ecr.aws/zebrunner/mcloud-device:2.5.3-beta3
public.ecr.aws/zebrunner/stf:2.5.3-beta2
```

**Comment by dhreben** [comment]
**Reopened**

Tested on iPhone 8

**Case 1:**

1. ./zebrunner.sh restart udid 

**Actual result:** Preparing status is absent on STF

**Case 2:**

1. ./zebrunner down udid
2. ./zebrunner start udid

**Actual result:** Preparing status is absent on STF

**Case 3:** 

1. Physically removing the WDA on Iphone 8
2. ./zebrunner.sh down udid
3. ./zebrunner.sh start udid

**Actual result:** Preparing status is absent on STF

**Case 4:**

1.  docker exec -ti device-iPhone_8-e18f6..........................addba8-appium bash
2. kill -9 wda pid

**Actual result:** Preparing status is absent on STF.  iOs device is not active with status **Use**

<img width="1241" alt="Screenshot 2023-10-11 at 10 35 31" src="https://github.com/zebrunner/stf/assets/50950954/59b13228-5cd6-442b-9c3b-d3a6240c3b45">

**Comment by dhreben** [comment]
re-Verified 
```
public.ecr.aws/zebrunner/stf:2.5.3-beta4
public.ecr.aws/zebrunner/mcloud-device:2.5.3-beta4
```

**Comment by dhreben** [comment]
re-Verified

public.ecr.aws/zebrunner/stf:2.5.3-beta4
public.ecr.aws/zebrunner/mcloud-device:2.5.3-beta4
