### ISSUE TITLE
from time to time detection of xml format for Info.plist is broken

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#416]
let's improve xml type detection for Info.plist. Instead of custom bash script we can reuse http://manpages.ubuntu.com/manpages/impish/man1/xmllint.1.html

**Comment by vdelendik** [comment]
fixed using xmllint utility

**Comment by vdelendik** [comment]
finally find elegant way to perform parser for both variants: https://github.com/zebrunner/stf/pull/436
Please, verify that for all test ipa files in browser Develop Tools -> Network -> Fetch/XHR valid non empty manifest response exists.

**Comment by dhreben** [comment]
**Veriied.**

Manifest has 200 status.
Info  about manifest is present:

<img width="1165" alt="Screenshot 2022-05-11 at 14 56 29" src="https://user-images.githubusercontent.com/50950954/167850284-1be6ccff-f19c-41a6-925b-fe9c21540d29.png">
