### ISSUE TITLE
Please add filter by Platform to the Customization

### ISSUE THREAD

**Issue by maksimsarychau** [zebrunner/stf#441]
Often we require filtering/sorting by Platform (Android or iOS) in STF. 

Please add it to the Customization

<img width="1484" alt="image" src="https://user-images.githubusercontent.com/4455896/166901085-70785f1c-5d07-4d09-9092-5ebf723e93af.png">

**Comment by vdelendik** [comment]
@danymill, let's try to implement in upcoming 2.4 release

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/stf/pull/659
we hve to determine why it is not available until `reset` is clicked

**Comment by dhreben** [comment]
Platform added and work correctly.
Reset button reset the last set filter on Customization
