### ISSUE TITLE
hide model name column for devices by default

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#451]
we replaced model by our custom device name. let's return original model name so we provide mare valuable information to users to analyze. Using model it is much faster to look for actual technical details etc

**Comment by vdelendik** [comment]
done. instead duplicating model and product we keep our devicename for Product column and model/brand name for Modal.
the most important part of testing - execution of mobile web tests vs concrete device using `deviceName=Nokia_3` capability for example.

**Comment by vdelendik** [comment]
change is not so easy so reverting and assigning to the next milestone

**Comment by vdelendik** [comment]
@ignacionar, instead of refactoring all kind of shell scripts and registration logic let's just make this column hidden by default. Make sure it becomes hidden after reset customization

**Comment by ignacionar** [comment]
**Done:** https://github.com/zebrunner/stf/pull/884

**Comment by vdelendik** [comment]
all good

**Comment by dhreben** [comment]
Verified.
