### ISSUE TITLE
unable to get logs via STF

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#455]
Activate logs and click get
-> websocket error appear

**Comment by vdelendik** [comment]
fixed in `zebrunner/stf:2.2-beta10`.
during the testing just activate Logs and click `Get`
-> all logcat log messages (upto verbose) should be displayed and runtime. after stop try to save them..

Pay attention that #459 submitted about broken filtering, i.e. if you provide any value for time/pid/tid or tag then functionality is still broken.

**Comment by dhreben** [comment]
Verified on Android devices
Unable to get logs via STF iOS devices

Relevant ticket was created https://github.com/zebrunner/stf/issues/473
