### ISSUE TITLE
unable to parametrize logcat by filters

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#459]
To fix #455 we hardcoded `2` (VERBOSE) and `*` (everything) as a tag:
```
activeLogcat.include(filter.tag, filter.priority)
->
activeLogcat.include("*", 2)
```

It allows to fix blocker and don't crash stf-websocket everytime we click get logcat logs...
but all existing fields including log level, time, pid, tid, tag and text can't be reused as a filter anymore... let's investigate what might be done (stf\res\app\control-panes\logs\logs-controller.js) to provide valid data

**Comment by vdelendik** [comment]
fixed: https://github.com/zebrunner/stf/commit/15f5a7942852b4a9f4255b8497af513384853059

using hardcoded verbose log level and * tag we could start listening logcat output... After that we can specify all kind of filters including log level, time, pid, tid, tag and text.

Testing scenario might be:
1. start streaming with default settings to see column data
2. try to specify concrete existing values as filter one by one, stop, clear logs and get logs again
-> only lines related to the filter are displayed
3. test with pairing filters choosing any 2 fields together
-> both filters should be applied for log output

**Comment by dhreben** [comment]
Verified all steps.
