### ISSUE TITLE
Error: Service is currently unavailable after click switch charset button on STF

### ISSUE THREAD

**Issue by dhreben** [zebrunner/stf#463]
**Steps:**

1. Open iOS device on STF
2. Click Advanced input settings
3. Click switch charset button 

**Actual result:** Error:service is currently unavailable after click switch charset button on STF

**NOTE**: Nothing happens after click switch charset button on **Android device**

<img width="898" alt="Screenshot 2022-05-16 at 13 05 39" src="https://user-images.githubusercontent.com/50950954/168570849-6a60cf03-9b36-4e62-9b47-b1a767294785.png">

**Comment by vdelendik** [comment]
fixed by above PR already. can be tested on v2.7

**Comment by dhreben** [comment]
Fix
