### ISSUE TITLE
Reset all browser button doesn't work after clicking on STF at iOS device

### ISSUE THREAD

**Issue by dhreben** [zebrunner/stf#464]
**Steps:**

1. Open iOS device on STF
2. Enter any site on navigation bar
3. Click reset all browser button

**Actual result:** Reset all browser button doesn't work after clicking on STF at iOS device

<img width="857" alt="Screenshot 2022-05-16 at 13 24 59" src="https://user-images.githubusercontent.com/50950954/168572980-9aeeb6bf-a76f-4cca-8eeb-8a8812ccd7b0.png">

**Comment by vdelendik** [comment]
merged. going to start new 2.4.6 milestone...

**Comment by dhreben** [comment]
Closed 
Reset all browser button is disabled
