### ISSUE TITLE
Normal mode/vibrate mode /silent mode buttons don't work after clicking on STF

### ISSUE THREAD

**Issue by dhreben** [zebrunner/stf#467]
**Steps:**

1. Open Android device on STF
2. Click Automation tab
3. Click normal mode/vibrate mode /silent mode buttons at device settings tab

**Actual result:** Normal mode/vibrate mode /silent mode buttons don't work after clicking on STF

**Note:** Repro on Android
- HTC_10

<img width="1187" alt="Screenshot 2022-05-16 at 17 20 53" src="https://user-images.githubusercontent.com/50950954/168614450-21c14fba-b274-4571-aa16-1eccb1baa5e0.png">

**Comment by vdelendik** [comment]
fixed by merged PR including HTC_10

**Comment by dhreben** [comment]
Fixed
