### ISSUE TITLE
Find device button doesn't work after clicking on STF at iOS device

### ISSUE THREAD

**Issue by dhreben** [zebrunner/stf#469]
**Steps:**

1.Open iOS device on STF
2.Click info  tab
3.Click Find Device buton on Physical Device tab

**Actual result:** Find device button doesn't work after clicking on STF at iOS device

**Note:**  Repro on iPhone 8 and IPhone 11,12,13 Pro on MFP

<img width="728" alt="Screenshot 2022-05-17 at 07 10 32" src="https://user-images.githubusercontent.com/50950954/168727213-efcdf3c7-fe67-45c9-8523-4548407c6b38.png">

**Comment by vdelendik** [comment]
@danymill, let's disable for iOS so far

**Comment by vdelendik** [comment]
proposed changes merged to `public.ecr.aws/zebrunner/stf:2.4.5-beta6`.
mcloud-deivice, mcloud-agent and CE, branch develop updated accordingly as well.
need to remove, clone recursively and setup from scratch to test.
@dhreben, let us know if works better otherwise we have to revert changes...

**Comment by vdelendik** [comment]
disabled find device button for iOS completely and reopened and moved to the next milestone for more stable solution.
based on the logs messages not delivered correctly to the ios-device plugin...

**Comment by dhreben** [comment]
Closed 
Find device button is disabled

**Comment by vdelendik** [comment]
reopening for rebuilding and closing

**Comment by vdelendik** [comment]
@dhreben PR merged, let's retest using stf:2.6.1

**Comment by dhreben** [comment]
Fixed on STF: 2.6.1 version
