### ISSUE TITLE
On LANDSCAPE mode clicks and swipes doesn't work correctly on springboard(home screen).

### ISSUE THREAD

**Issue by alexmalynovskyi** [zebrunner/stf#48]
### brief description :
Was found that on iPhone 7/8 or early doesn't work properly LANDSCAPE mode on spring board. It 
caused by absence of LANDSCAPE mode on these devices. But in others applications where is LANDSCAPE mode clicks and swipes works properly.

**Comment by vdelendik** [comment]
closed as dupe to keep in one ticket
