### ISSUE TITLE
introduce new Unhealthy status for device

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#483]
during the automation runs we might detect device status when it is available for remote manual usage but can't be used by automation, for example: too low disk space, some network/wifi connectivity issues etc.
in this case we wanna to have:
1. new status Unhealthy (5) which allow to do remote connect but without possibility to execute test automation (1 - offline; 2 - unauthorized; 3 - use, 4 - connected)
  Note: exact state name TBD
3. api end-point to change the status (take a look to #300 howto change status)
4. change UI to highlight this status. Using from `Unauthorized` should be good enough but with ability to use device manually.

**Comment by ignacionar** [comment]
**Done:** https://github.com/zebrunner/stf/pull/798

Changes are available in `public.ecr.aws/zebrunner/stf:2.6-beta1`

**Comment by vdelendik** [comment]
closing, @dhreben - find a way to validate. ideally I'd like to see api call to change state to unhalthy

**Comment by dhreben** [comment]
It will be verified after the execution https://github.com/zebrunner/stf/issues/825

**Comment by dhreben** [comment]
Verified.
Curl -X PUT -H "Authorization: Bearer <token>" -H 'Content-Type: application/json' -d '{ "device": { "status": "Unhealthy" } }' https://demo.zebrunner.farm/api/v1/devices/<udid> | jq .
