### ISSUE TITLE
unable to delete iOS device via api

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#484]
subj

**Comment by vdelendik** [comment]
fixed in `stf:2.3-beta3` by https://github.com/VbKoshak/stf/commit/febee158fdee4db37cffc788b21db8b7ad4f82b9

**Comment by dhreben** [comment]
**Test scenario:**

1.. cd Mcloud 
2. nano .env
3. set stf:2.3-beta3 
4. ./zebrunner.sh restart

Actual result:  ERROR: manifest for zebrunner/stf:2.3-beta3 not found: manifest unknown: manifest unknown

Logs :  

```
Pulling stf-app (zebrunner/stf:2.3-beta3)...
ERROR: manifest for zebrunner/stf:2.3-beta3 not found: manifest unknown: manifest unknown
```

**Comment by vdelendik** [comment]
@dhreben let's test again. latest `zebrunner/stf:2.3-beta12` is pushed to docker hub

**Comment by dhreben** [comment]
Verified.

```
(base) build@mcloud:~/tools$ curl --location --request DELETE 'https://demo.zebrunner.farm/api/v1/devices/b09fa..............f862b5' \
> --header 'Authorization: Bearer f2c4e47.................eeb93'
{"success":true,"description"
```
