### ISSUE TITLE
All checkbox are absent on customise settings

### ISSUE THREAD

**Issue by dhreben** [zebrunner/stf#493]
**Steps:**

1. Open STF
2. Click Customise button

**Actual result:** All checkbox are absent on customise settings

**Note:**
Repro: Chrome 102v
On safari looks good! 

<img width="1272" alt="Screenshot 2022-06-07 at 13 24 32" src="https://user-images.githubusercontent.com/50950954/172357978-853ce085-1c0e-4f48-8705-a171e6051f54.png">

**Comment by vdelendik** [comment]
fixed indirectly

**Comment by dhreben** [comment]
Fixed
