### ISSUE TITLE
On distributed setup stop using not return device on ui

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#505]
On distributed setup it was discovered that stop using not always make device available on ui. Extra refresh needed to make it happen.

we have to review websocket signals for stop/start using and make sure it is send and received

**Comment by vdelendik** [comment]
issue is repro on single host deployment as well. some notes to observation include:
1. during opening device we open two websocket connection:
wss://demo.zebrunner.farm/socket.io/?uip=%3A%3Affff%3A172.18.0.30&EIO=3&transport=websocket
wss://demo.zebrunner.farm/d/demo.zebrunner.farm/FA74SBN02369/7424/

2. during stop usage both of them should be closed
3. in case `wss://demo.zebrunner.farm/socket.io/?uip=%3A%3Affff%3A172.18.0.30&EIO=3&transport=websocket` continue to be in pending state we observe not finished usage on ui until we refresh the page

**Comment by vdelendik** [comment]
seems like fixed indirectly with #547

**Comment by dhreben** [comment]
Fixed.
Open relevant ticket  https://github.com/zebrunner/stf/issues/549
