### ISSUE TITLE
reuse dockerized usbmuxd service benefits

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#535]
https://github.com/zebrunner/mcloud-agent/issues/127

we were able to define required steps to share usbmuxd into the appium container and share it via tcp using socat.
let's review all go ios utility usage keeping in mind that only single device is visible, i.e. as minimal remove `--udid=..` arg.

also don't install usbmuxd on stf container side

**Comment by vdelendik** [comment]
done. it should be tested using mcloud from branch develop.
after setup iOS device:
1. shouldn't be available via `ios list` on master host
2. should be available inside appium container (using usbmuxd and shared device)
3. should be available inside stf container (using socat connection to appium usbmuxd socket)

also it make sense to test over iOS device:
1. Advanced->reboot
2. ipa install and launch operations

**Comment by dhreben** [comment]
Test scenario:

1.ios list is not available on master host
```
(base) build@mcloud:~/tools$ ios list
{"err":"dial unix /var/run/usbmuxd: connect: no such file or directory","level":"fatal","msg":"failed getting device list","time":"2022-08-05T18:24:11+03:00"}
```
2. Usbmuxd available inside appium container 
```
docker exec -ti device-iPhone_8-b09fa26a............f862b5-appium bash
root@6924f4dae7a5:~# ios list
{"deviceList":["b09fa26acc...................3f862b5"]}
```
3. Socat connection to appium usbmuxd socket  verified  with @vdelendik  
4. Restart ios device doesn't work after click Advanced->Restart device button
  - Relevant ticket was reopened https://github.com/zebrunner/stf/issues/275 
5. Error: Service is currently unavailable! Try your attempt later after install app via STF
 - Relevant ticket was reopened https://github.com/zebrunner/stf/issues/244
