### ISSUE TITLE
remove `store account` fields

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#538]
`Store Account` fields don't work for a long period of time. we can remove them from UI at all

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/stf/pull/540/files
![image](https://user-images.githubusercontent.com/4551455/182161082-ba49776f-becd-4d26-a8bd-3ac4aef8bcc2.png)

changes are available in `zebrunner/stf:2.3-beta7`

**Comment by dhreben** [comment]
Verified.
