### ISSUE TITLE
move `Device Settings` from Automation to Advanced

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#539]
we can remove completely Automation tab moving `Device Settings` to Advanced.
Still TBD if we need `Appium URL` data at all

**Comment by vdelendik** [comment]
as appium url completely removed we can move `Device Settings` and completely remove Automation tab

**Comment by vdelendik** [comment]
strange css and color after adding device settings on dvanced tab:
![image](https://user-images.githubusercontent.com/4551455/207214992-90284dc4-2796-402c-bc76-905083266d57.png)

**Comment by vdelendik** [comment]
done, verify that controls are displayed on advanced tab

**Comment by dhreben** [comment]
Verified
