### ISSUE TITLE
init battery status for iOS

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#542]
we fixed battery level detection but didn't reuse state in #289.

curl --location -g --request GET 'http://192.168.89.19:8100/session/37096496-B665-41A3-A9A1-C013DDD7B103/wda/batteryInfo'
{
  "value" : {
    "level" : 1,
    "state" : 3
  },
  "sessionId" : "37096496-B665-41A3-A9A1-C013DDD7B103"
}

let's register such fields:
source: USB
Status: Full (3); Charging (2) based on state in response
Temp: -

**Comment by vdelendik** [comment]
done.
we hardcoded "usb" as a source, "good" as health and "n/a " as temperature:
https://github.com/zebrunner/stf/pull/543/files#diff-c0e662c394d4f7f25b37555bc7982efa0f05f9595025a9cb82e9c4fec91884c4R110

level and state is calculating based on wda client response.
![image](https://user-images.githubusercontent.com/4551455/182198472-84ad7e19-b1f6-4a92-a226-50eebac1e23a.png)

**Comment by dhreben** [comment]
Verified.
