### ISSUE TITLE
Gray screen for android device until hide/show clicked

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#547]
it was discovered that device.using field might be updated with delay and as result we don't start onScreenInterestGained.

**Comment by vdelendik** [comment]
fixed. @dhreben during the testing investigate start/stop using from different screens and using different users. Occupied devices shouldn't be available for regular user and only admin might to connect into the same session

**Comment by dhreben** [comment]
Verified with admin and different users on 3 browsers: Сhrome,Safari and Opera.
