### ISSUE TITLE
iPad: The incorrect screen resolution displays on the info state

### ISSUE THREAD

**Issue by dhreben** [zebrunner/stf#551]
**Steps:**

1. Open STF
2. Open  iPad device
3 Click info button

**Actual result:** The incorrect screen resolution (height/width ) displays on the info state

<img width="1352" alt="Screenshot 2022-08-05 at 16 56 27" src="https://user-images.githubusercontent.com/50950954/183092190-495c40ce-60ff-460c-9c9a-cb18c12039f1.png">

**Comment by vdelendik** [comment]
closed in scope of #326 fix. please, use testing scenario from that ticket as well.

**Comment by dhreben** [comment]
Verified.

![Screenshot 2022-08-09 at 15 52 18](https://user-images.githubusercontent.com/50950954/183651523-f0ad6b42-21e2-42f6-b607-d699e9940401.png)
