### ISSUE TITLE
widht/height not inited during startup

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#556]
we can't capture widht/height of the device display before we start wda session. as result after initial registration and connect we have nothing on Info tab and any 1st action on device crash.
after automatic restart after that device is fully operational. related ticket are: #326, #292, #551

let's investigate how can we capture widht/height and scaling factor in advance so device registration is good from scratch.

**Comment by vdelendik** [comment]
4.10.0+ WDA implemented size detection without sessionId:
reuse benefits of new WDA: https://github.com/appium/WebDriverAgent/pull/625
https://github.com/appium/WebDriverAgent/releases/tag/v4.10.0

let's try to upgrade to the latest 4.12.0 and reuse new `/window/size` end point

**Comment by vdelendik** [comment]
let's concentrate on width/height detection on setup or startup... if possible it would be great to reuse values from rethinkdb and don't do extra call att all for` /window/size`

**Comment by vdelendik** [comment]
refactored code: https://github.com/zebrunner/stf/pull/681/files
@dhreben, please retest carefully operations related to "startSession", "batteryIosEvent", "size" and "swipe"

**Comment by vdelendik** [comment]
1. read info about iOS device from rethink db if any
2. reuse already existing width/heigh and skip extra wda call `/wda/size`
3. only if not exists widht/height then do a call and init value
4. do not override width/heigh everytime we connect to iOS device

**Comment by KostyaSha** [comment]
Probably you can create table because resolutions are fixed for device models i.e. https://gist.github.com/ricsantos/e7baee6885626b9cb87c021a5097623f

**Comment by ignacionar** [comment]
The following [draft changes](https://github.com/zebrunner/stf/compare/develop...ignacionar:stf:%23556) intend to either update size values or retrieve them. The only blocker is to send the `response` from `wire.SizeIosDevice` to WdaClient context.

**Comment by dhreben** [comment]
`Storing device size/scale ` is present in logs after first start device,  but device crashed, also we have nothing on STF / info
```
Width = px 
Height =px
```
`2023-12-22T17:18:36.716Z INF/wdaClient 35 [e18f63d.............deaddba8] Storing device size/scale`
All steps are done on iPhone_8, I haven’t done one on Iphone_8_plus yet, left it for you to re-produce 
Logs ans video are provided on slack

**Comment by ignacionar** [comment]
**Done:** https://github.com/zebrunner/stf/pull/862

**Comment by dhreben** [comment]
**Tested on stf:2.6.2-beta10, mcloud-device:2.6.2-beta10**

Verified.

**Comment by ignacionar** [comment]
**Done:** https://github.com/zebrunner/stf/pull/909

**Comment by dhreben** [comment]
Still repro

**Comment by ignacionar** [comment]
**Done:** https://github.com/zebrunner/stf/pull/921

With this approach, no reload is required now. Size and Device Type values will be set in DB and reused as well.

**Comment by dhreben** [comment]
**Tested**
docker build . -t public.ecr.aws/zebrunner/stf:2.6.4-beta32
docker build . -t public.ecr.aws/zebrunner/mcloud-device:2.6.4-beta32

` Unhandled rejection TypeError: Cannot read properties of undefined (reading 'message')`

**Comment by vdelendik** [comment]
improved including negative cases.

**Comment by dhreben** [comment]
Verified.
