### ISSUE TITLE
The app installed to another iOS device after install via STF

### ISSUE THREAD

**Issue by dhreben** [zebrunner/stf#564]
**Test scenario:**

1. Open STF
2. Open Iphone 11
3. Click drop file to upload
4. Select ipa.file

**Actual result:**  The app installed to another iOS device after install via STF

**Note:** The app installed to iPhone 11_2

**Comment by vdelendik** [comment]
fixed. deployed already changes on stag (mcloud-ios).
@dhreben, please test this concrete use-case for devices connected to mcloud-ios and obligatory repeat on the same devices connected via Linux.
app install and automatic launch and ios device reboot were affected

**Comment by dhreben** [comment]
Verified.
