### ISSUE TITLE
bump up to v1.0.80+ go-ios

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#603]
Let's investigate an option to reuse feature from: https://github.com/danielpaulus/go-ios/releases/tag/v1.0.80
```
the old repo wasn't well maintained and images were not working or deprecated. 
Using https://github.com/mspvirajpatel/Xcode_Developer_Disk_Images now for the `image auto` command. 
```

it would be great to avoid our own responsibility from developer images upload/download and move management onto the go-ios level

https://github.com/danielpaulus/go-ios/releases/tag/v1.0.97
```
Added a new endpoint to REST API that allows to pair (un)supervised devices 
```

**Comment by vdelendik** [comment]
done. testing should include CE and mcloud setup and connect any ios device. if device might be used in manual mode we can close it.

**Comment by dhreben** [comment]
Will be verified after fixed https://github.com/zebrunner/community-edition/issues/532 and https://github.com/zebrunner/appium/issues/154

**Comment by dhreben** [comment]
Verified.
