### ISSUE TITLE
everytime we do stop using search field is activated

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#643]
that's pretty annoying because after activation of the search field it display some kind of hint:
![image](https://user-images.githubusercontent.com/4551455/206290171-d0b4c4af-7305-4740-a3b2-b937eebe458b.png)

let's don't make it active after stop using

**Comment by vdelendik** [comment]
fixed indirectly after removal of Appium Url in #234 ticket. try to activate search, find something, activate searched device and do stop usage via different buttons and modes

**Comment by dhreben** [comment]
Still repro.
The search field is activated after  stop using device, but hint is not displayed.

**Comment by vdelendik** [comment]
if no hint displayed then everything is good. the mot annoying was this dropdown. closing...
@dhreben ^^^

**Comment by vdelendik** [comment]
reopened. after several hours of usage dropdown is displayed as well

**Comment by vdelendik** [comment]
fixed: https://github.com/zebrunner/stf/pull/661
fix is available in `stf:2.4-beta13`+

**Comment by dhreben** [comment]
Fixed
