### ISSUE TITLE
move device to `Disconnected` state asap after down

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#649]
integrate device movement into the `Disconnected` state right after down command

**Comment by vdelendik** [comment]
fixed by changing the stop order. first of all we should stop wda and as result iOS device moved to disconnected asap.
during the testing test the same for Android. If it doesn't work for android - submit new ticket

**Comment by dhreben** [comment]
**Test scenario:**

 **IOS:** 

1. docker exec -ti device..-appium bash
2. ios list
3. ios kill $WDA_BUNDLEID

**Expected result:** WDA stopped ,appium - container restarted. The iOS device restarted and active on STF

**Android:**

Steps:

1 .docker exec -ti device..-appium bash
2.  pkill -9 -f appium

**Expected result:** WDA stopped ,appium - container restarted. The Android device restarted and active on STF
