### ISSUE TITLE
Android device is available during 60sec  on STF after ./zebrunner.sh stop/down udid

### ISSUE THREAD

**Issue by dhreben** [zebrunner/stf#664]
**Steps:**

1../zebrunner.sh stop/down udid
2. Verify that Android device is not available 

Actual result:  Android device is available during 60sec on STF after ./zebrunner.sh stop/down udid

**Comment by vdelendik** [comment]
@dhreben it was fixed in scope of mcloud-agent [v2.5](https://github.com/zebrunner/mcloud-agent/releases/tag/2.5).
we changed an order of the stopped/removed containers to start with appium which guarantee stf detects new disconnected state asap
