### ISSUE TITLE
Add wss websocket auto re-connection for wda mjpeg

### ISSUE THREAD

**Issue by danymill** [zebrunner/stf#666]
If a device was restored after disconnection we need to close this window automatically (re-connect programmatically)
I.e. instead of error message let's try to disable display and display dynamic loading icon for the next 5-10s and only after that raise an exception.

Auto-recovery should be started asap and loading and reconnecting should be displayed on stf-app level

![image](https://user-images.githubusercontent.com/6594800/209581001-b654041b-4371-4668-bb5d-b73314f5db6a.png)

**Comment by dhreben** [comment]
**Steps:**

**Case 1:**

1. Open STF
2. Open iphone_8
3. `docker exec -ti device-iPhone_8-e18f63dd2e441bea17f95a50b1073bbbdeaddba8-appium bash`
4. `ps -ef`
5. ` kill -9 75 `. - wda
6. Wailting 10 sec when wda is restarter automatically
7. Click Try to connect button

**Expected result:**  iphone _8 available on STF and displays screen

**Case 2:** 

1. Open STF
2. Open iphone_8
3. Reconnect iphone
4. Waiting 30-40 sec when container device up and running
5. Click Try to connect button

**Expected restult:** iphone _8 available on STF and displays screen
