### ISSUE TITLE
MacOS: integrte recovery kickstart for every WDA crash

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#671]
Attaching logs when using stf on MacOS. Ideally we can capture all failures in one place and do recovery kickstart for reanimation
[crash.log](https://github.com/zebrunner/stf/files/10404428/crash.log)

kickstart recovery implementation is here https://github.com/zebrunner/stf/pull/665/files.

**Comment by vdelendik** [comment]
so far ignored session id null on delete because we are doing it's removal. let's keep for a while this ticket if we really need to kickstart recovery on every crash

**Comment by vdelendik** [comment]
let's integrate for every wda crash in scope of this ticket

**Comment by vdelendik** [comment]
done. to test we have to do mass actions and emulate wda crash... quick opening, typing, swiping etc...
during the action do tailing `tail -f  ./logs/<device>.log`
right after every crash device should be recovered and available again in 8-10s

**Comment by dhreben** [comment]
Steps

1. Click any media button on Advanced tab
2. WDA is crached

**Expected result**:  iOs device is restarted and up and running on STF
