### ISSUE TITLE
remove code related to GetIosTreeElements

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#675]
as we removed Tree tab we can remove all code related to `GetIosTreeElements` in  stf/lib/units/ios-device/plugins/wda.js

**Comment by ignacionar** [comment]
**Done:** https://github.com/zebrunner/stf/pull/698

**Comment by vdelendik** [comment]
`stf:2.4.4-beta3` is available for testing in mcloud (develop branch). The same for Zebrunner CE (branch: develop).
Make sure to pull mcloud-agent as well because is has fresh mcloud-device image and rerun ansible

**Comment by dhreben** [comment]
Verified. Did basic acceptance including manual usage inside STF
