### ISSUE TITLE
iOS speedup typing functionality 

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#676]
iOS typing is rather problematic. it sends chars via actions keyup/keydown actions every char. And as we can't control the order of the wda requests/responses chars are typed in wrong order, i.e. qwerty -> qewryt etc

let's refactor typeKeys making it as fast as possible and typing in valid order chars

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/stf/pull/677/files
we reused keyUp/keyDown actions and organized flush actions by word or after 100ms delay.

as result speed is great and quality is very good. @dhreben, let's try to type `Hello World!` on any old env and new one and collect both timing and quality... using fast approach on old we definitely type with a mistakes...

**Comment by dhreben** [comment]
I have tested the old approach and the new one. 
Hello world - old ->12sec
Hello world -new -> 8 sec
The result with the new approach is definitely 50 percent faster tiping
