### ISSUE TITLE
AppleTV: unable to do tap 

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#688]
Let's investigate if tap is supported or not. it might be a limitation of TV box where only arrow buttons work.
In attach 
[appletv.log](https://github.com/zebrunner/stf/files/10454986/appletv.log)
you can find an exception for the tap over the application on AppleTV:

**Comment by vdelendik** [comment]
we can later discuss and maybe display `Remote Control` buttons in menu. As of step one it seems ok... 
merged and built `public.ecr.aws/zebrunner/stf:2.4.5-beta4`. @dhreben, please re-setup CE using develop branch from scratch. mcloud-agent and mcloud-ios should be pulled and re-setup(ed) as well...

**Comment by dhreben** [comment]
Verified.
