### ISSUE TITLE
AppleTV: test and identify all applicable WDA commands

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#689]
full list of available commands can be find in `*.m` files:
https://github.com/appium/WebDriverAgent/tree/a1824895274c60798b506f31054e4ce1e0400c71/WebDriverAgentLib/Commands

we have to test each of them and detect all supported for AppleTVю
For example how commands are filtered inside appium code:
```
#if !TARGET_OS_TV // tvOS does not provide relevant APIs
    [[FBRoute POST:@"/wda/setPasteboard"] respondWithTarget:self action:@selector(handleSetPasteboard:)],
    [[FBRoute POST:@"/wda/getPasteboard"] respondWithTarget:self action:@selector(handleGetPasteboard:)],
    [[FBRoute GET:@"/wda/batteryInfo"] respondWithTarget:self action:@selector(handleGetBatteryInfo:)],
```

**Comment by vdelendik** [comment]
```
curl --location -g --request GET 'http://localhost:7411/session/8A6305C2-96AC-4A7B-8CA0-30BE379D9136/element/active'
{
  "value" : {
    "ELEMENT" : "0C000000-0000-0000-5A36-000000000000",
    "element-6066-11e4-a52e-4f735466cecf" : "0C000000-0000-0000-5A36-000000000000"
  },
  "sessionId" : "8A6305C2-96AC-4A7B-8CA0-30BE379D9136"
}


curl --location -g --request GET 'http://localhost:7411/session/8A6305C2-96AC-4A7B-8CA0-30BE379D9136/element/0C000000-0000-0000-5A36-000000000000/attribute/focused'
{
  "value" : true,
  "sessionId" : "8A6305C2-96AC-4A7B-8CA0-30BE379D9136"
}


curl --location -g --request GET 'http://localhost:7411/session/8A6305C2-96AC-4A7B-8CA0-30BE379D9136/element/0C000000-0000-0000-5A36-000000000000/text'
{
  "value" : "Sign Up Now",
  "sessionId" : "8A6305C2-96AC-4A7B-8CA0-30BE379D9136"
}

[[FBRoute POST:@"/element/:uuid/click"] -> doesn't work
```

**Comment by ignacionar** [comment]
**Not working endpoints:**

- `/wda/homescreen`

- `/wda/lock`

- `/wda/batteryInfo`

- `/wda/setPasteboard`

- `/wda/getPasteboard`

- `/wda/siri/activate`

- `/wda/apps/launchUnattached`

**Working endpoints:**

- `/wda/screen`

- `/wda/locked`

- `/wda/pressButton`

- `/wda/device/info`

**Comment by vdelendik** [comment]
let's keep for a while in open state to understand which one we can't use for AppleTV...

**Comment by vdelendik** [comment]
closing as we already automated as much as possible inside stf ios-device plugin,

**Comment by dhreben** [comment]
1.  **/wda/locked, screen, device/info** are work correctly.
2. **/wda/pressButton** - Left button and up button doesn't work when click behind the apple TV area. The relevant tickets have been created https://github.com/zebrunner/stf/issues/740  and https://github.com/zebrunner/stf/issues/739
3. All buttons that were disabled for iOS devices are also disabled for AppleTV

This ticket will be closed after fixing  https://github.com/zebrunner/stf/issues/739 https://github.com/zebrunner/stf/issues/740

**Comment by dhreben** [comment]
Closed
https://github.com/zebrunner/stf/issues/739 - done
https://github.com/zebrunner/stf/issues/740 -  closed
