### ISSUE TITLE
Change Apple TV (Apple Watch ) logos to more relevant according to STF design.

### ISSUE THREAD

**Issue by dhreben** [zebrunner/stf#690]
STF Apple TV(Apple Watch ) logos look the same as on iOS devices. It would be great to change to a more relevant, according  to STF design

<img width="619" alt="Screenshot 2023-01-20 at 01 13 19" src="https://user-images.githubusercontent.com/50950954/213574714-aa42f737-7f83-4b52-9a6d-3c180e344f83.png">

**Comment by vdelendik** [comment]
![apple_TV_24x24](https://user-images.githubusercontent.com/4551455/220895241-bd13992e-4138-4464-9f28-738539db11fd.png)
![apple_TV_93x90](https://user-images.githubusercontent.com/4551455/220895243-a550a2a6-c1b9-493e-8a16-c485a29050b8.png)
![apple_TV_13x13](https://user-images.githubusercontent.com/4551455/220895244-47b02540-b226-4f4c-9805-cc02de94c86d.png)


proposed files attached^^^

**Comment by vdelendik** [comment]
done. changes already applied on demo server.

**Comment by dhreben** [comment]
Verified
