### ISSUE TITLE
Upload all types files in android device 

### ISSUE THREAD

**Issue by Manish1804Tcb** [zebrunner/stf#709]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by vdelendik** [comment]
@Manish1804Tcb, please explain in detals which files and how you want to upload? so far only apk upload and install are supported.

**Comment by vdelendik** [comment]
closing as won't fix due to the lack of the requested information.
