### ISSUE TITLE
Camera image injection feature

### ISSUE THREAD

**Issue by Manish1804Tcb** [zebrunner/stf#710]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by vdelendik** [comment]
@Manish1804Tcb, not enough information. Please, explain in detils what you wanna to see with this feature. Thanks!

**Comment by vdelendik** [comment]
closing as won't fix due to the not enough information, @Manish1804Tcb.
