### ISSUE TITLE
Back and Recents buttons crash any iOS device/simulator

### ISSUE THREAD

**Issue by ignacionar** [zebrunner/stf#728]
**Steps to reproduce:** 

**1.** Click right button in the device screen.

**2.** Click on "back" or "recents" button.

<img width="161" alt="Captura de pantalla 2023-04-20 a la(s) 17 19 38" src="https://user-images.githubusercontent.com/85379690/233636657-3e3c49de-c297-4259-938a-1737d5a3ebf1.png">

**Comment by ignacionar** [comment]
**Done:** https://github.com/zebrunner/stf/pull/730

**Comment by vdelendik** [comment]
changes are available in 2.4.6-beta2
