### ISSUE TITLE
AppleTV: The up button doesn't work when click behind the apple TV area

### ISSUE THREAD

**Issue by dhreben** [zebrunner/stf#739]
Steps:

1. Open STF
2. Open AppleTV
3. Open menu
4. Try to click behind the apple TV area

**Actual result:**  The up button doesn't work when click behind the apple TV area

Please see screenshot:

<img width="464" alt="Screenshot 2023-04-27 at 16 47 38" src="https://user-images.githubusercontent.com/50950954/234882970-73c2166d-5445-4505-8caf-067fce5384f8.png">

**Comment by ignacionar** [comment]
**Done:** https://github.com/zebrunner/stf/pull/741
