### ISSUE TITLE
iOS:  The long serial number does not fit within the hardware tab

### ISSUE THREAD

**Issue by dhreben** [zebrunner/stf#745]
**Steps:**

1. Open STF
2. Open iOS device
3. Click info tab

**Actual result:** The long serial number does not fit within the hardware tab

<img width="909" alt="Screenshot 2023-05-12 at 12 13 01" src="https://github.com/zebrunner/stf/assets/50950954/79b02943-3a97-4f37-be9f-903fc3641eb1">

**Comment by vdelendik** [comment]
fix should be available in `stf:2.4.7-beta3`.
p.s. make sure to clean cache before testing!

**Comment by dhreben** [comment]
Fixed
