### ISSUE TITLE
Apple TV : Incorrect action after tap home button on STF

### ISSUE THREAD

**Issue by dhreben** [zebrunner/stf#749]
**Steps:**

1. Open STF
2. Open Apple TV
3. Open Settings
4. Open General
5. Try to click Home button (blue button on STF) to return to the the previous page (Settings)

**Actual result:**  Incorrect action after tap home button on STF. After pressing the Home button we redirect to the Apple TV menu directly. 

**Expected result:**  After  pressing the Home button it should return to the previous menu. If we are  in Settings and click home button, it should exit to the Apple TV menu.

Please see screenshots:

**Actual result:** 

<img width="1011" alt="Screenshot 2023-05-17 at 17 00 55" src="https://github.com/zebrunner/stf/assets/50950954/524d5a92-7dcf-4c17-853c-2b95afe2da2d">

**Expected result:** 

<img width="962" alt="Screenshot 2023-05-17 at 17 09 00" src="https://github.com/zebrunner/stf/assets/50950954/5c0c7841-afc5-4b6f-b4b8-0b9c25668688">

**Comment by ignacionar** [comment]
**Done: ** https://github.com/zebrunner/stf/pull/751

**Comment by dhreben** [comment]
Fixed
