### ISSUE TITLE
Apple TV : Different main UI buttons will crash 

### ISSUE THREAD

**Issue by ignacionar** [zebrunner/stf#754]
Since `/orientation` and `/getPasteboard` WDA endpoints do not exist for Apple TV devices, clicking these buttons will cause a crash.

<img width="77" alt="Captura de pantalla 2023-07-06 a la(s) 15 17 15" src="https://github.com/zebrunner/stf/assets/85379690/7c0960cd-ca0e-4c17-b1ec-fb704a61fd4d">

<img width="584" alt="Captura de pantalla 2023-07-10 a la(s) 14 53 19" src="https://github.com/zebrunner/stf/assets/85379690/dac1cff5-d878-41d9-9712-f108e75e00e7">

**Comment by ignacionar** [comment]
**Done: ** https://github.com/zebrunner/stf/pull/755

**Comment by ignacionar** [comment]
Disabled items for Apple TV:

- Rotation buttons
- Clipboard input
- Switch charset button

**Comment by dhreben** [comment]
Verified.
