### ISSUE TITLE
Enhance shutdown process via long Press on Power Button in "Advanced Tab"

### ISSUE THREAD

**Issue by dhreben** [zebrunner/stf#764]
Currently, after clicking the Power button on the advanced tab, the device's screen becomes locked,  it would be great to try to shutdown device using long click Power button.

<img width="620" alt="Screenshot 2023-08-07 at 15 45 42" src="https://github.com/zebrunner/stf/assets/50950954/df1ed40b-7cc0-4fe7-88b0-b1b4d6361159">

**Comment by vdelendik** [comment]
still under the question if shutdown is really needed for remote action...

**Comment by vdelendik** [comment]
after deeper discussions we decided not to implement shutdown for the mcloud... reboot is the only way to shutdown and start.
