### ISSUE TITLE
landscape mode is not properly detected during reopening

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#770]
Original portrait/landscape switcher functionality is available according to #177.

Let's review more complicated scenario to make it workable

if we open device and switch mode then it works correctly
problems begin when you close device in landscape and open again
-> it seems like on opening we don't init mode correctly.
Let's investigate if we can detect mode on opening and init height/width or forcibly revert to portrait on every open to

steps:

open device and start safari in portrait mode
-> operations are ok
switch to portrait
-> operations are ok
close device
open device again
-> landscape is displayed; operations not ok
change to portrait
-> operations not ok
close and open
-> operations ok
@dhreben, I suppose we can resolve this original and submit new one to make sure we support landscape during reopening...
Also, make sure to clean cache to test original functionality...

**Comment by ignacionar** [comment]
**Done: ** https://github.com/zebrunner/stf/pull/774 , now the device resets to Portrait mode when closing it

**Comment by dhreben** [comment]
Reopened

**Steps:**

1. Open iPhone 8 on STF
2. Open Safari
3. Click Landscape mode
4. Click Stop using button
5. Open iPhone one more time

**Expected result:** iOS device  resets to Portrait mode when closing it

6. Open iPhone 8 with opened safari
7. Click landscape mode
8. Click stop using button
9. Open iPhone one more time

**Actual result:** iOS device opened on Landscape mode after closing it

Also, opened separate ticket https://github.com/zebrunner/stf/issues/801

**Comment by ignacionar** [comment]
**Done:** https://github.com/zebrunner/stf/pull/804/commits

Added a small delay to reset the device rotation before session ends.

**Comment by dhreben** [comment]
Fixed
