### ISSUE TITLE
ios: reuse offline state for the case when device connected and wda not accessible

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#775]
in scope of global optimization and don't streaming wda everytime we can reuse offline state.
i.e. as only wda crashed/stopped/killed but device physically connected to the server (visible via `ios list`) we can move device into the Offline state in stf.

**Comment by ignacionar** [comment]
**Done:** https://github.com/zebrunner/stf/pull/797

The device now uses Offline state when its connected and WDA crashes

**Comment by dhreben** [comment]
Verified.
