### ISSUE TITLE
The screen of the device has decreased in size after click home button on Landscape mode

### ISSUE THREAD

**Issue by dhreben** [zebrunner/stf#801]
**Steps:**

1. Open iphone_8 on STF
2. Click Safari or Photos
3. Click Landscape button - > device has turned to Landscape mode
4. Click Home button

**Actual result**: The screen of the device has decreased in size after click home button on Landscape mode
Please see screenshot  

**Expected result:**  iOS device  resets to Portrait mode when click home button

I believe this will be the correct behavior because not all  ios devices can support Landscape mode in the main menu

<img width="438" alt="Screenshot 2023-10-25 at 17 53 11" src="https://github.com/zebrunner/stf/assets/50950954/0e0f6408-30d1-440d-806b-2b9d034528c0">

**Comment by ignacionar** [comment]
**Done:** https://github.com/zebrunner/stf/pull/802

Now the device orientation gets reset properly

**Comment by dhreben** [comment]
Steps:

1. Open iphone_8_plus on STF
2. Click Safari or Photos
3. Click Landscape button - > device has turned to Landscape mode
4. Click Home button -> device resets to Portrait mode
5. Click wallet button on main menu   - > Calendar is opened

Actual result: Incorrect behavior after  pressing any button when reset device to Portrait mode from Landscape mode

**Comment by ignacionar** [comment]
**Done:** https://github.com/zebrunner/stf/pull/805 and https://github.com/zebrunner/stf/pull/813

**Comment by dhreben** [comment]
Fixed
