### ISSUE TITLE
Samsung_Tab_A7 screen does not respond on STF

### ISSUE THREAD

**Issue by gawlikj** [zebrunner/stf#806]
**Steps:**

1. Open Samsung_Tab_A7 on STF
2. Click/tap on any app on the device's screen

**Actual result:**
Device is not responding to any actions on its screen via tap/click

**Expected result:**
Apps can open and screen can be scrolled through

**Comment by dhreben** [comment]
Closed, as now is ok with Samsung_Tab_A7
