### ISSUE TITLE
Logs doesn't work on HTC10 

### ISSUE THREAD

**Issue by amastej** [zebrunner/stf#810]
**Steps** 
1. Open STF and click on HTC10
2. Go to "Logs" and click "Get"
3. Open console > network

**Actual result**
The first request almost never displays logs. To display logs we need to select something from the list and click on "GET" once again.   
<img width="1440" alt="Zrzut ekranu 2023-11-30 o 12 21 35" src="https://github.com/zebrunner/stf/assets/149781148/8057fbcd-a5a8-4a6b-a650-125e45b09234">

https://github.com/zebrunner/stf/assets/149781148/9fb6aaf6-3b37-46a3-b5ca-f6bb7befc324

**Expected result**
The logs are visible for user and available to save after the first click on "GET"

**Comment by amastej** [comment]
Sometimes the logs open after pressing "GET" 2-3 times

**Comment by vdelendik** [comment]
closing as won't fix. that's a combination of HTC and very old Android 8
