### ISSUE TITLE
Wifi disable button doesn't work on Pixel 7 and Samsung Tab A7 

### ISSUE THREAD

**Issue by amastej** [zebrunner/stf#811]
**Steps**
1. Open STF and click on Pixel 7A
2. Go to Advanced Tab 
3. In Device Settings click on "Disable WiFi"
4. Click on "Stop using" and repeat that with Samsung Tab A7

**Actual result**
Wif disable button doesn't work on Pixel 7 and Samsung Tab A7

**Expected result**
Wifi disable button turns off WiFi on Pixel 7 and Samsung Tab A7

**Comment by vdelendik** [comment]
closing as won't fix. there many ways to make it happen including opening wi-fi settings via button on Dashboard tab, swiping from the top and opening via settings...
