### ISSUE TITLE
make sorting user-friendly

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#816]
existing sorting logic is rather strange. it seems like sort by 1st Status column always enabled.
I'd like to have ability to sort by every column independently

**Comment by ignacionar** [comment]
Changes included in `stf:2.6.2-beta2` and `mcloud-device:2.6.2-beta2`. mcloud, and CE - branch develop.
Remember to clean cache for testing new changes.

**Comment by ignacionar** [comment]
Additional fix for #816: https://github.com/zebrunner/stf/pull/855

Now the status column stores rows correctly when reloading the page.

**Comment by ignacionar** [comment]
Columns are now reset for any user and busy devices rows are stored when reloading: https://github.com/zebrunner/stf/pull/856

**Comment by ignacionar** [comment]
PR: https://github.com/zebrunner/stf/pull/857

In order to test, follow these steps:

1. Delete cookies and `localStorage` data (or also in new incognito window).
2. Once you enter, check selected columns -> click `Reset`

**Comment by dhreben** [comment]
1. Devices view after refresh 1 device is shown, after click Details and Devices -> all devices are shown  -> **Fixed**
2. Devices view LG_G6 shows internal device name - G6Fit -> **Fixed** 
3. Sorting should be case insensitive, iPhones should be after H - **Fixed** 
4. Start using not mark device as busy... ~1 min required - **Still Repro**

**Comment by dhreben** [comment]
Verified.

**Tested on stf:2.6.2-beta8, mcloud-device:2.6.2-beta8**
Start using not mark device as busy... ~1 min required - **Fixed**
