### ISSUE TITLE
Mobile: landscape/portrait mode, hide screen and "stop using" button are not displayed 

### ISSUE THREAD

**Issue by amastej** [zebrunner/stf#833]
**Steps**
1. On your mobile log in with valid credentials to STF
2. Open any device e.g Pixel 7a

**Actual result** 
User cannot see landscape/portrait mode, hide screen and "stop using" button when using simulator via mobile device
<img width="324" alt="Zrzut ekranu 2023-11-30 o 10 56 39" src="https://github.com/zebrunner/stf/assets/149781148/3e9f42c1-ffa0-410c-b5ac-e6c2cf6ff1f5">

**Comment by dhreben** [comment]
implemented for testing:

- public.ecr.aws/zebrunner/stf:2.7.2-beta9
- public.ecr.aws/zebrunner/mcloud-device:2.7.2-beta9

**Comment by dhreben** [comment]
Fixed
