### ISSUE TITLE
No e-mail address when contacting support

### ISSUE THREAD

**Issue by amastej** [zebrunner/stf#839]
**Steps**
1. Open STF with valid credentials
2. On menu click on "Contact Support" 

**Actual result**
E-mail window opens but with undefined e-mail address 
<img width="836" alt="Zrzut ekranu 2023-11-29 o 10 24 08" src="https://github.com/zebrunner/stf/assets/149781148/09b2f2fa-013d-4b20-9225-2a7c51bd44a8">

**Expected result**
E-mail window opens with visible e-mail address to support _support@zebrunner.com_

**Comment by ignacionar** [comment]
**Done:** https://github.com/zebrunner/stf/pull/905

**Comment by amastej** [comment]
works properly
