### ISSUE TITLE
Blank pages open in Help, Access Token and ADB Keys

### ISSUE THREAD

**Issue by amastej** [zebrunner/stf#840]
**Preconditions**
Open STF and log in with valid credentials

**Steps** 
1. On menu click on "Help" 
2. Go back to main page and go to Settings section
3. Open Keys tab and click on "More about Access Token" (icon)
4. Go back to Keys tab and click on "More about ADB Keys" (icon)

**Actual result**
Help, Access Token and ADB Keys pages are blank 
<img width="1222" alt="Zrzut ekranu 2023-11-30 o 11 06 08" src="https://github.com/zebrunner/stf/assets/149781148/21898273-0d0f-430c-8452-20a2ec89c66d">

**Expected result**
User has access to Help, Access Token and ADB keys pages

**Comment by vdelendik** [comment]
closing as vendor issue (stf itself). we don't plan to fix it in our fork
