### ISSUE TITLE
Save filtering on page refresh

### ISSUE THREAD

**Issue by azarouski** [zebrunner/stf#846]
Please, add possibility to save filter state after page refresh.
<img width="367" alt="image" src="https://github.com/zebrunner/stf/assets/99244081/d3320cc4-1270-439d-9e6d-94dbd959870a">

**Comment by ignacionar** [comment]
**Done:** https://github.com/zebrunner/stf/pull/887

**Comment by dhreben** [comment]
Verified
Tested on
 STF=2.6.4-beta2
Mcloud-device 2.6.4-beta2
