### ISSUE TITLE
Battery level is not visable on iPhone

### ISSUE THREAD

**Issue by amastej** [zebrunner/stf#849]
**Steps**
1. Open STF
2. Choose iPhone 8,  iPhone 8 plus or iPhone 11
3. Go to Info tab and battery level

**Actual result**
Battery level is not visable on all iPhone's
<img width="1223" alt="Zrzut ekranu 2023-12-4 o 11 40 09" src="https://github.com/zebrunner/stf/assets/149781148/58f538e7-96e9-428c-b6a8-fb1049e0e925">
<img width="1225" alt="Zrzut ekranu 2023-12-4 o 11 41 51" src="https://github.com/zebrunner/stf/assets/149781148/1875d6a3-79ca-4b32-99fb-f2af4e360d32">

**Expected result**
Battery level is visable in all iPhone's

**Comment by vdelendik** [comment]
converted to enhancement, not sure wda allow to read suc kind of information

**Comment by dhreben** [comment]
Implemented for testing:

public.ecr.aws/zebrunner/stf:2.7.1-beta1
public.ecr.aws/zebrunner/mcloud-device:2.7.1-beta1

**Comment by dhreben** [comment]
Verified
