### ISSUE TITLE
Add information about invalid password during log in

### ISSUE THREAD

**Issue by amastej** [zebrunner/stf#850]
If you enter an incorrect password when logging in, the system provides information about a _server error_ instead of : 
"We do not recognize that username or password.
Please check your spelling and try again or use another login option."
<img width="474" alt="Zrzut ekranu 2023-12-4 o 15 57 35" src="https://github.com/zebrunner/stf/assets/149781148/c8eb96f3-6bbc-417f-b7a3-7f860fdd23e8">

**Comment by dhreben** [comment]
Verified.

<img width="384" alt="Screenshot 2024-06-04 at 14 25 55" src="https://github.com/zebrunner/stf/assets/50950954/0b80045a-b17e-46d2-82f9-be847f3c1750">
