### ISSUE TITLE
reuse previous scrolling state when opening Devices from Details tab

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#871]
with new sorting functionality we display devices based on user input without automatic jumps...
at the same time after clicking to "Devices" tab we always scroll to the top automatically.

it would be great to remember previous scrollbar state to jump onto the same state and see reently occupied device. Problem might be discovered only on the farms with 50-70 devices when scroll is displayed on the Details tab

steps:
1. login into any farm where we have 50+ devices
2. activate Details tab 
3. scroll down for several pages and occupy device
4. Click onto the global Devices button
-> we jump onto the top and to see currently occupied device we have to scroll down

Expected behavior
-> Previous scroll bar state should be used and recently activated device should be visible

**Comment by ignacionar** [comment]
**Done:** https://github.com/zebrunner/stf/pull/893

Details tab scroll bar state should remain now.

**Comment by dhreben** [comment]
@amastej available for testing
implemented new:
mcloud-device:2.6.4-beta11
STF:2.6.4-beta11

**Comment by dhreben** [comment]
@amastej available for testing
implemented new:
mcloud-device:2.6.4-beta17
STF:2.6.4-beta17

**Comment by amastej** [comment]
Works with a slight delay on some devices
