### ISSUE TITLE
Settings does not opens on Samsung S5 via Apps tab

### ISSUE THREAD

**Issue by amastej** [zebrunner/stf#876]
**Steps**
1. Open STF and open Samsung S5
2. In dashboard go to "Apps" and click on "Settings" 

**Actual result**
Settings does not opens on Samsung S5 via Apps tab

https://github.com/zebrunner/stf/assets/149781148/b8cbd8bb-9da8-48fc-8002-24ed34b31110

**Expected result**
Settings opens on Samsung S5 via Apps tab

**Comment by vdelendik** [comment]
closing as won't fix. too old android, no need to fix as settings might be opened in UI
