### ISSUE TITLE
Creating Access Token - Title field accepts blank spaces and does not clear input once created

### ISSUE THREAD

**Issue by gawlikj** [zebrunner/stf#880]
**Steps:**
1. Open STF
2. Go to Settings tab and choose Keys
3. Click on the + to add a new Access Token
4. In the Title field enter few blank spaces and click Generate New Token
5. Click on the + to add a new Access Token again
6. Create a token called e.g. 'Test'
7. Repeat steps 5. and 6.
8. Click 'Remove' next to the previously created token 'Test'

**Actual Results:**

- Title field accepts blank spaces
- Title field holds the previously entered value when adding next token
- If more than one token have the same Title - removing one will delete all that have the same Title

**Expected Results:**

- Title field should not accept blank spaces 
- Title field values should be cleared after each added token 
- Only token next to which we click 'Remove' should be deleted regardless of other token Titles

https://github.com/zebrunner/stf/assets/140834345/6f4ea8fd-751d-442f-b0c9-e1ebe8219a07

**Comment by vdelendik** [comment]
nc, @gawlikj !

**Comment by dhreben** [comment]
implemented for testing:
- public.ecr.aws/zebrunner/stf:2.7.2-beta6
- public.ecr.aws/zebrunner/mcloud-device:2.7.2-beta6

**Comment by dhreben** [comment]
Still not fixed:
- Title field values should be cleared after each added token
- Only token next to which we click ‘Remove’ should be deleted regardless of other token Titles

**Comment by dhreben** [comment]
implemented for testing:

- public.ecr.aws/zebrunner/stf:2.7.2-beta7
- public.ecr.aws/zebrunner/mcloud-device:2.7.2-beta7

**Comment by dhreben** [comment]
Fixed
