### ISSUE TITLE
Show/Hide screen works selectively on iOS 17

### ISSUE THREAD

**Issue by amastej** [zebrunner/stf#888]
**Steps**
1. Open STF and log in 
2. Select device with iOS 17 (iPhone 11 or iPhone SE)
3. Click on "show/hide" icon 

**Actual result**
System works selectively on devices with iOS 17

https://github.com/zebrunner/stf/assets/149781148/570ee258-3d17-40f7-a7c0-decb01142732

**Expected result**
Show/Hide screen works correctly

**Comment by ignacionar** [comment]
The `hide screen` button is working correctly (disconnect from websocket). 

When toggling to `show screen` the reconnection to the stream takes more time than others iOS devices (however, it reconnects and shows the screen after a couple of seconds).

https://github.com/zebrunner/stf/blob/5190eac8e09f4c93c3b799c71f44a38b84be04f8/res/app/components/stf/screen/screen-directive.js#L355

This will be faster or slower depending on the device's environment.

**Comment by vdelendik** [comment]
Speed depends on resolution that’s why on small screens like SE it is pretty fast.

**Comment by ignacionar** [comment]
@vdelendik It would be possible to just hide the device screen (css) instead of closing the WS connection. Should we just stick to the current approach or hide with css styles?

**Comment by vdelendik** [comment]
@dhreben, could you please retest. As I remember @ignacionar fixed iOS websocket reconnect stuff.
Goal to keep consistency and as in Android disconnect/connect websocket.

**Comment by dhreben** [comment]
Fixed
