### ISSUE TITLE
Malfunction when zooming screenshots on LG G6s

### ISSUE THREAD

**Issue by amastej** [zebrunner/stf#891]
**Steps**
1. Open LG G6s on STF
2. Go to 'Screenshots' tab and take for example 8 or more screenshots
3. Zoom in the screenshot using the +/- sliding bar in top right corner to the max value and look on screenshots

Comment: hard to reproduce

**Actual result**
Screenshots appear in a different size

https://github.com/zebrunner/stf/assets/149781148/903b02c2-f765-44c2-8c6c-4be0ab92640d

**Expected result**
All screenshots are the same size

**Comment by vdelendik** [comment]
@amastej, nice finding! I really like it :)
But still no resources to fix such kind of problems in open source application. closing as won't fix
