### ISSUE TITLE
Landscape icon switches to portrait when changing screen arrangement on all iPhones

### ISSUE THREAD

**Issue by amastej** [zebrunner/stf#892]
**Steps**
1. Log in STF and open any iPhone 
2. Open any website e.g google.com and click on "landscape icon"

**Actual results**
the icon jumps from portrait to landscape

https://github.com/zebrunner/stf/assets/149781148/3c4b6298-05a2-4b52-999c-e55fcd92ddc9

**Expected result**
The screen position changes smoothly

**Comment by dhreben** [comment]
implemented for testing:

- public.ecr.aws/zebrunner/stf:2.7.2-beta5
- public.ecr.aws/zebrunner/mcloud-device:2.7.2-beta5

**Comment by dhreben** [comment]
Fixed
