### ISSUE TITLE
remove device-type ios-device cli arg and reuse call to wda to detect and save device type.

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#897]
Earlier we used command go ios call to read info and parse ios device type:
https://github.com/zebrunner/mcloud-device/pull/187/files#diff-4398bd4cabd7d1c063c4d3f7a973b9f6f27dfd06f3ac03d2f3fd5e26b6a52f72L117

nowadays wda allow to do it though the end-point:
```
  #### Detect device type
  wdaDeviceInfo=$(curl -sf http://${WDA_HOST}:${WDA_PORT}/wda/device/info)
  device=$(echo "$wdaDeviceInfo" | jq -r ".value.model")
```
https://github.com/zebrunner/mcloud-device/pull/187/files#diff-4398bd4cabd7d1c063c4d3f7a973b9f6f27dfd06f3ac03d2f3fd5e26b6a52f72R116

@ignacionar, let's simplify logic by:
1. removing --devicre-type cli arg completely for ios-device class
2. integrate `http://${WDA_HOST}:${WDA_PORT}/wda/device/info` call inside wdaclient for the 1st time for new device (for already populated - read data from db)
3. after reading device type according to the logic above, put value into the rethinkdb

related tickets:
https://github.com/zebrunner/mcloud-device/issues/170
https://github.com/zebrunner/mcloud-device/issues/162

**Comment by ignacionar** [comment]
**Done:** https://github.com/zebrunner/stf/pull/901

- When setting a new device, logs will display: `Setting device type value: <type>`
- When reusing a device, logs will display: `Reusing device type value <type>`

A new STF API endpoint can be tested with: `curl http://<baseUrl>/api/v1/devices/<udid>/type`, and should return `{"deviceType": "iPhone"}` or `{"deviceType": "Apple TV"}` on success.

**Comment by vdelendik** [comment]
@dhreben, PR merged

**Comment by dhreben** [comment]
Verified
 `curl https://de.......................m/api/v1/devices/6d1e6edc......................216/type`
