### ISSUE TITLE
Find device button not working on Samsung S21

### ISSUE THREAD

**Issue by amastej** [zebrunner/stf#913]
**Steps**
1. Log in STF 
2. Open Samsung S21
3. Click on "info" than on "find device" 

**Actual result**
Find device button not working on Samsung S21

https://github.com/zebrunner/stf/assets/149781148/3ba19ff9-7757-4ecf-a03b-bf5633d91bbf

**Expected result**
Find device button works properly

**Comment by vdelendik** [comment]
@amastej, closing as vendor issue. it seems like finder application doesn't work on this particular device. we don't support this application.
