### ISSUE TITLE
iOS: mismatch in model and product names.

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#918]
@ignacionar, please take a look onto the naming registration. it seems like with new approach we lost syncup for the Product column name.
<img width="592" alt="image" src="https://github.com/zebrunner/stf/assets/4551455/452a3780-3860-47c6-84d5-06968d982fbd">

it would be great to have everywhere the same name as in the yml configuration files.

**Comment by ignacionar** [comment]
**Done:** https://github.com/zebrunner/stf/pull/919, 

remember to remove localstorage and cookies

**Comment by vdelendik** [comment]
merged, stf:2.6.4 republished

**Comment by dhreben** [comment]
Fixed

**Comment by dhreben** [comment]
Reopened
Mismatch model and product names in STF and  yml.file

**Comment by dhreben** [comment]
Reopened

let’s implement the mapping in stf as set by the user in main.yml, both with and without _

**Comment by vdelendik** [comment]
fixed on mcloud-agent and mcloud-device levels:
https://github.com/zebrunner/mcloud-device/issues/207, https://github.com/zebrunner/mcloud-agent/issues/359

current implementation inside stf is valid.
@ignacionar, fyi^^

**Comment by dhreben** [comment]
implemented for testing:
- public.ecr.aws/zebrunner/stf:3.0
- public.ecr.aws/zebrunner/mcloud-device:3.0

**Comment by dhreben** [comment]
Reopened

**Steps:**

Mac case: 

1. Open main.yml - Enter name : iPhone_XR.  -> **with underscore** - > Device is displayed without underscore
2. Open main.yml - Enter name : iPhone SE  -> **with space** - > Device isn't available on STF

Linux case:

1. Open main.yml - Enter name : iPhone_11.  -> **with underscore** - > Device is displayed without underscore
2. Open main.yml - Enter name : iPhone 7 Plus  -> **with space** - > Device isn't available on STF

**Comment by dhreben** [comment]
implemented for testing:
- public.ecr.aws/zebrunner/stf:3.0-beta2
- public.ecr.aws/zebrunner/mcloud-device:3.0-beta2

**Comment by dhreben** [comment]
**Linux case:**

1. iPhone_7_ Plus  ->device is  available on STF
2. iPhone 7 Plus  -> device is available on STF
3. iPhone_7 Plus  -> device is available on STF
4. Samsung_Galaxy_S22 -> device is available on STF
5. Samsung Galaxy S22  -> device is available on STF
6. Samsung _Galaxy S22 -> device is available on STF

Automation is  tested with all cases, also tested  iPhone_12(with underscore) and iPhone 12(with space) cases on 18 ios version.Basic acceptance successfully completed. Video, screenshots and logs are available.

**Mac case:**

Steps:

1. Open main.yml 
2. Enter  iOS device name with space -> iPhone SE
3. Run ansible script
4. ./zebrunner.sh start

**Actual result**: iOS containers are not up. Docker: invalid reference format: repository name must be lowercase.

```
solvd@idmcloud mcloud-agent % ./zebrunner.sh start

Device with udid: '00008030001C35AE3C42402E' was SUCCESSFULLY detected as connected.
grep: SE-00008..............2402E: No such file or directory
grep: SE-0000................402E: No such file or directory
grep: SE-000................402E: No such file or directory

	Creating '0000.............402E' containers:

wdaIpaPath: /Users/idmcloud/tools/WebDriverAgent.ipa
wdaBundleId: com.facebook.WebDriverAgentRunner.xctrunner

device-iPhone SE-0000...............C42402E-mitm:       docker: invalid reference format: repository name must be lowercase.
See 'docker run --help'.
already created
device-iPhone SE-00...............42402E-connector:  docker: invalid reference format: repository name must be lowercase.
See 'docker run --help'.
already created
device-iPhone SE-000.............3C42402E:            docker: invalid reference format: repository name must be lowercase.

```

**Comment by dhreben** [comment]
Moved to Ready for QA.
Will be fix after https://github.com/zebrunner/mcloud-agent/issues/359

**Comment by dhreben** [comment]
Reopened 

@azarouski 
Fyi @ignacionar 
**Linux case:**

1. Open nano/roles/device/vars/main.yml

- iPhone_11 ->  device is available on STF but displayed iPhone 11
- iPhone_8 -> device is available on STF but displayed iPhone 8

**Mac case:**

1. Open nano/mac-roles/device/vars/main.yml

- iPhone SE ->  device is available on STF but displayed iPhone_SE

**Comment by azarouski** [comment]
@ignacionar 
about Linux case:
For some devices we can see in response [additional data](https://github.com/zebrunner/stf/blob/50c6489384e0c2c8d2871f13937435d29cb77bcf/lib/util/datautil.js#L21) and if these devices in [DB](https://github.com/DeviceFarmer/stf-device-db/blob/master/data/devices-latest.json#L15309) STF ignoring our custom name and gets name for them from this DB [info](https://github.com/DeviceFarmer/stf-device-db/blob/master/data/devices-latest.json#L15334). Please, pay attention to underscore.

**Comment by dhreben** [comment]
Implemented for testing: 

- public.ecr.aws/zebrunner/stf:3.0-beta3

**Comment by dhreben** [comment]
Still repro

**Linux case:**

- `Open nano/roles/device/vars/main.yml`

**iPhone_11** or **iPhone_8**  -> devices are available on STF, but displayed **iPhone 11** or **iPhone 8,**
but when used  **iPhone_11_2** or **iPhone_8_2**  -> 2 undersсores - STF is displayed correctly ->  **iPhone_11_2** or **iPhone_8_2**

**Comment by dhreben** [comment]
Implemented for testing:

- public.ecr.aws/zebrunner/stf:3.0-beta4

**Comment by dhreben** [comment]
Fixed
