### ISSUE TITLE
capture device type error detection and exit with status 0 or 1

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#924]
https://github.com/zebrunner/stf/blob/15480e0ab5e8d57548fd78f32890525bd44a6b19/lib/units/ios-device/plugins/wda/WdaClient.js#L788

as a hotfix I injected device type detection and storing data in db... we have to review again the functionality to make sure we read from DB for every new services startup... Seems like current implementation will ask wda for that anyway 1st time

**Comment by vdelendik** [comment]
@dhreben, changes are in `stf:2.6.5-beta1` and `mcloud-device:2.6.5-beta1` images

**Comment by dhreben** [comment]
Verified
