### ISSUE TITLE
The "Stop Using" via device button does not always make the device available on the list again

### ISSUE THREAD

**Issue by amastej** [zebrunner/stf#930]
**Steps**
1. Open STF and log in with valid credentials
2. Open any device, e.g Samsung S7
3. On device click "stop using"
4. Look on device list
5. Open other device and again click on "stop using"

**Actual result**
Sometimes the "stop using" button does not stop the device. To do this, open another one and then click "stop using".
We then see that both devices are ready to work.

https://github.com/zebrunner/stf/assets/149781148/55749eb7-73ce-4d98-9613-fea4e700da5d

**Comment by ignacionar** [comment]
**Done:** https://github.com/zebrunner/stf/pull/936/commits

**Comment by dhreben** [comment]
Merged for testing: 

public.ecr.aws/zebrunner/stf:2.6.6-beta4
public.ecr.aws/zebrunner/mcloud-device:2.6.6-beta4
