### ISSUE TITLE
It would be good if the user could see the progress bar in "Groups"

### ISSUE THREAD

**Issue by amastej** [zebrunner/stf#931]
Currently, when logging into STF and going to the "Groups" tab, despite the current, active group belonging to the Admin, the user does not see the progress of the bar.
It would be good if it could be seen that the current admin group is present on the progress bar
<img width="1293" alt="Screenshot 2024-03-20 at 13 16 41" src="https://github.com/zebrunner/stf/assets/149781148/24efa2d1-bd42-4713-8400-7c1c338974bc">

**Comment by vdelendik** [comment]
closing as won't fix.
