### ISSUE TITLE
iPhone 8 plus disconnects when repeatedly clicking on the "screenshot" button

### ISSUE THREAD

**Issue by amastej** [zebrunner/stf#934]
**Steps**
1. Log in to STF
2. Open iPhone 8 plus 
3. Click on "Screenshot" tab 
4. Tap "screenshot" quickly and repeatedly

**Actual result**
iPhone 8 plus disconnects when repeatedly clicking on the "screenshot" button

https://github.com/zebrunner/stf/assets/149781148/3d6ef569-bf11-4006-83c1-27e488652e05

**Comment by dhreben** [comment]
Merged for testing:
public.ecr.aws/zebrunner/mcloud-device:2.6.6-beta3
public.ecr.aws/zebrunner/stf:2.6.6-beta3

**Comment by amastej** [comment]
We can only take 1 screenshot at a time. Works correctly
