### ISSUE TITLE
iPhone_8 and 8 plus disconnects when click "mute" several times

### ISSUE THREAD

**Issue by amastej** [zebrunner/stf#938]
**Steps**
1. Log in to STF
2. Open iPhone_8_plus or iPhone 8 and go to "Advanced" tab
3. Click several times on "mute" 

**Actual result**
iPhone disconnects when click "mute" several times

https://github.com/zebrunner/stf/assets/149781148/4965f8a8-a87b-4310-a8c1-7b74b296dc14

**Comment by dhreben** [comment]
Implemented to test: 
public.ecr.aws/zebrunner/stf:2.6.6-beta5
public.ecr.aws/zebrunner/mcloud-device:2.6.6-beta5

**Comment by dhreben** [comment]
fixed
