### ISSUE TITLE
Die Rotate Die

### ISSUE THREAD

**Issue by ugotfluxxed-lol** [zebrunner/stf#941]
unless disabled manually devices auto-rotate as if possessed
 
through experimentation with V4 we determined that if disabled device would remain portrait unless rotate button was pressed

this  overrides manual disable

-------------------------------------------
&&
------------------------------------------
No devices on Mobile

**Comment by dhreben** [comment]
**implemented for testing:**
- public.ecr.aws/zebrunner/stf:2.7.2-beta4
- public.ecr.aws/zebrunner/mcloud-device:2.7.2-beta4

**Comment by dhreben** [comment]
Testes on Samsung_Tab_A7
Fixed
