### ISSUE TITLE
Mobile: Navigation tabs are not available when using STF on phone

### ISSUE THREAD

**Issue by amastej** [zebrunner/stf#942]
**Steps**
1. Open STF on your phone and log in
2. Click on any device 

**Actual result**
The user does not have access to navigation tabs
![IMG_1959](https://github.com/zebrunner/stf/assets/149781148/916dcf81-3ecf-4eac-be21-c02c12a6c582)

**Expected**
navigation tabs are available to user
<img width="1224" alt="Screenshot 2024-04-08 at 11 50 31" src="https://github.com/zebrunner/stf/assets/149781148/08816929-a48b-41f9-bfcf-434e964986fd">

**Comment by dhreben** [comment]
Fixed
