### ISSUE TITLE
Mobile: Top bar is not available for user when using devices on phone 

### ISSUE THREAD

**Issue by amastej** [zebrunner/stf#943]
**Steps**
1. Open STF on your mobile device
2. Click on e.g Samsung S6

**Actual result**
The user can't see top bar 
![IMG_1959](https://github.com/zebrunner/stf/assets/149781148/92479cac-fdea-4aef-baf6-e21ecaf8f5f3)

**Expected result**
User see all top bar when using STF on his device 
<img width="1225" alt="top bar" src="https://github.com/zebrunner/stf/assets/149781148/8146e79f-d6b9-4083-80c9-d4f7357a375d">

**Comment by dhreben** [comment]
**implemented for testing:**

public.ecr.aws/zebrunner/stf:2.7.0-beta2
public.ecr.aws/zebrunner/mcloud-device:2.7.0-beta2

**Comment by dhreben** [comment]
Fixed
