### ISSUE TITLE
Mobile: Customize and Details are not available when using STF on mobile device

### ISSUE THREAD

**Issue by amastej** [zebrunner/stf#944]
**Steps**
1. Open STF on mobile device
2. Look on main page

**Actual result**
Customize and Details are not available for user
![IMG_1958](https://github.com/zebrunner/stf/assets/149781148/4473f262-a8e1-4f30-a15a-0aaad27d2d19)

**Expected result**
<img width="1221" alt="customize" src="https://github.com/zebrunner/stf/assets/149781148/494902f6-1c2c-4a85-9eb5-a325213ae013">

**Comment by dhreben** [comment]
Fixed

<img width="363" alt="Screenshot 2024-04-30 at 12 01 07" src="https://github.com/zebrunner/stf/assets/50950954/4332f18c-20e0-4231-ad8b-d1a6af9de0b2">

**Comment by dhreben** [comment]
Fixed

<img width="363" alt="Screenshot 2024-04-30 at 12 01 07" src="https://github.com/zebrunner/stf/assets/50950954/4332f18c-20e0-4231-ad8b-d1a6af9de0b2">
