### ISSUE TITLE
iOS: left and right buttons click on keyboard don't work on browser URL 

### ISSUE THREAD

**Issue by dhreben** [zebrunner/stf#952]
**Steps:**

1. Open STF
2. Open iPhone_8
3. Open browser
4. Try to click left or right buttons on browser URL

**Actual result:**  Left and right buttons  click on keyboard don't work on browser URL 

<img width="364" alt="Screenshot 2024-04-24 at 15 12 19" src="https://github.com/zebrunner/stf/assets/50950954/1e18dc8b-ef73-41c2-a572-973694cbe94f">

**Comment by ignacionar** [comment]
Should be closed as won't fix, there are no character values for Left, Right, Down and Up buttons of the keyboard. 

The endpoint we use for typing keys only receives [characters or their ascii code](https://appium.readthedocs.io/en/latest/en/commands/interactions/actions/#:~:text=actions%5B%24INDEX%5D.actions%5B%24INDEX%5D.value). The keys don't have these values.

**Comment by vdelendik** [comment]
closing as won't fix according to @ignacionar comment
