### ISSUE TITLE
Bottom control panel is not functioning

### ISSUE THREAD

**Issue by azarouski** [zebrunner/stf#961]
<img width="1512" alt="Screenshot 2024-05-17 at 17 23 25" src="https://github.com/zebrunner/stf/assets/99244081/17083d14-d457-404c-bc10-df175647ccd1">
panel in red rectangle not functioning now

**Comment by dhreben** [comment]
**implemented for testing:**
- public.ecr.aws/zebrunner/stf:2.7.0-beta7
- public.ecr.aws/zebrunner/mcloud-device:2.7.0-beta10
