### ISSUE TITLE
ios: Incorrect touch point detection on screen on iPhone 17v

### ISSUE THREAD

**Issue by dhreben** [zebrunner/stf#965]
When tap on the screen iPhone 17v , the touch point is detected incorrectly, causing apps to open higher than the intended touch point.

Steps:

1. Open iPhone 11
2. Tap on Settings - > **App Store is opened**

**Actual result:**    ios: Incorrect touch point detection on screen on iPhone 17v

<img width="361" alt="Screenshot 2024-05-21 at 18 37 09" src="https://github.com/zebrunner/stf/assets/50950954/0359da58-9b9b-4dc1-862b-df6d0a368b3b">

**Comment by vdelendik** [comment]
moved to 2.7.1 as can't reproduce in 2.7 on some environments

**Comment by dhreben** [comment]
Can't repro. Closed.
