### ISSUE TITLE
Isn't  possible to delete device using the STF UI

### ISSUE THREAD

**Issue by dhreben** [zebrunner/stf#969]
**Steps:**

1. Create SuperAdmin
2. Open STF use SeperAdmin creads
3. Click Settings
4. Click devices
5. Select device e.g Apple TV and click remove button

**Actual result:**  Device is not deleted. Nothing happens when click delete button.

<img width="346" alt="Screenshot 2024-05-22 at 20 26 23" src="https://github.com/zebrunner/stf/assets/50950954/6103c801-ab85-4a78-9be3-cf1a43cd8a9e">

**Comment by ignacionar** [comment]
The device will be deleted only according to the filters selection:

https://github.com/user-attachments/assets/b956fcd8-d488-4e1d-8034-c06bea7ccd23

The above delete button will delete all devices according to the filters, or you can only delete one device as shown in the video.

**Comment by vdelendik** [comment]
@dhreben, please review above comment^^^

**Comment by dhreben** [comment]
Can't repro. Closed
