### ISSUE TITLE
invalid condition of 1st time device usage and as result width/height can't be detected

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#971]
in case of iOS 17 where we start wda independently via xcode we'va found a problem with width/height detection.
it seems like we have a version but don't have sizes and as result this condition is broken:
https://github.com/zebrunner/stf/blob/eae9a9adb3152d5e729dca3c564c7b6df3084191/lib/units/ios-device/plugins/group.js#L75

![image](https://github.com/zebrunner/stf/assets/4551455/4b923139-819b-46d9-b4de-e367da824dd5)

**Comment by dhreben** [comment]
Implemented for testing:
- public.ecr.aws/zebrunner/stf:2.7.1-beta3
- public.ecr.aws/zebrunner/mcloud-device:2.7.1-beta2

**Comment by dhreben** [comment]
Fixed
<img width="221" alt="Screenshot 2024-06-06 at 16 28 20" src="https://github.com/zebrunner/stf/assets/50950954/a0654d27-4e77-4b7c-8e0c-e4113fe75fa1">
