### ISSUE TITLE
improve edit operation for the `Note` column to show edit icon in the beginning of control

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#973]
For ong Notes we started to send using appium we can't update them later manually as no horisontal scroll and as result no way to click on edit icon
![image](https://github.com/zebrunner/stf/assets/4551455/62e09ee9-1359-41cc-a3db-5376057c6d3f)

as workaround I'd recommend to display edit icon in the beginning on the Note control

**Comment by dhreben** [comment]
Implemented for testing:
- public.ecr.aws/zebrunner/stf:2.7.1-beta4
- public.ecr.aws/zebrunner/mcloud-device:2.7.1-beta4

**Comment by dhreben** [comment]
Verified.

<img width="808" alt="Screenshot 2024-06-07 at 11 59 04" src="https://github.com/zebrunner/stf/assets/50950954/b54576a5-fd63-40eb-9236-c07c6f7a3df8">
