### ISSUE TITLE
iOS: freeze UI during wda swiping

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#980]
we already added some fixes on beckend, ignoring any actions until wda finishes swipe correcly.
as result user might tap, type etc without any reaction.

@ignacionar, can we implement any screen freze (adding similar to loading icon over). It should provide a feedbacl to the user that no more actions possible, please wait.

**Comment by dhreben** [comment]
implemented for testing:
- public.ecr.aws/zebrunner/stf:2.7.2-beta3
- public.ecr.aws/zebrunner/mcloud-device:2.7.2-beta3

**Comment by dhreben** [comment]
Verified.
